### ISSUE TITLE
Write automated tests

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#102]

**Comment by rpotter12** [comment]
I tried to write an automated test but this software needs to scan the QR code which I as unable to thing how to do that in automated test.

**Comment by xandao6** [comment]
![image](https://user-images.githubusercontent.com/22106326/72234139-58dfdd00-35aa-11ea-830d-067db42b1602.png)
I think this can be done now, this is my last branch, I haven't pulled it yet but it's all working.

**Comment by xandao6** [comment]
This issue will be worth points for each written test.

**Comment by poojasrinivass** [comment]
I would like to work on this issue.

**Comment by xandao6** [comment]
@poojasrinivass assigned, you have 4 days + renew if there is no one in queue

**Comment by HarsheetKakar** [comment]
Can I take it on?

**Comment by poojasrinivass** [comment]
I need a little more time to work on it

**Comment by HarsheetKakar** [comment]
Tell me the ones u are working on and i will do the others. Points for each test remember?

**Comment by poojasrinivass** [comment]
I have tried to do multiple. So you pick what you want and I will continue with the rest.

**Comment by HarsheetKakar** [comment]
> ![image](https://user-images.githubusercontent.com/22106326/72234139-58dfdd00-35aa-11ea-830d-067db42b1602.png)
> I think this can be done now.
> I just pulled the experimental branch, take a look, I had a hard time doing that hehehe

Is it working now? Because im still having the same issue of QR code

**Comment by poojasrinivass** [comment]
Can you tell me what you're working on?

**Comment by xandao6** [comment]
Both of you are working on this issue?

**Comment by HarsheetKakar** [comment]
sorry for the delayed response,
I am figuring out the application at the moment, will directly send the PR if I make any progress... if thats ok

**Comment by poojasrinivass** [comment]
> Both of you are working on this issue?

I am still working on it.

**Comment by SinghHimadri** [comment]
Can I also work on this issue if there are points for each test case?

**Comment by xandao6** [comment]
@HarsheetKakar your turn, @poojasrinivass unassigned

**Comment by HarsheetKakar** [comment]
@xandao6 I am already working on an issue ATM, would it be ok if someone else can do it?

**Comment by SinghHimadri** [comment]
I am interested.

**Comment by priyansh19** [comment]
@xandao6 please assign this to @himadrisingh she had started working on it :)

**Comment by xandao6** [comment]
@SinghHimadri assigned

**Comment by xandao6** [comment]
@SinghHimadri Do you will continue to work in this issue?

**Comment by SinghHimadri** [comment]
Yes, I am writing more tests I would request you to keep me assigned.
