### ISSUE TITLE
Create an executable for windows

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#105]

**Comment by xandao6** [comment]
If we do this: #111
Than #105 can be done easily with pyinstaller

**Comment by amruta-n** [comment]
Interested for working on this issue... Could you provide details?

**Comment by xandao6** [comment]
Assigned to you, read about "Pyinstaller"

**Comment by amruta-n** [comment]
Ok I'll do it, thank you

**Comment by xandao6** [comment]
@amruta-n deadline extended +4d

**Comment by brainaxe123** [comment]
Read about pyinstaller, would like to work on this issue.

**Comment by xandao6** [comment]
@brainaxe123 added to queue

**Comment by xandao6** [comment]
@brainaxe123 assigned

**Comment by SnegaRamesh** [comment]
i would like to work on this

**Comment by meghanagottapu** [comment]
@xandao6 can I work on this issue?

**Comment by xandao6** [comment]
@SnegaRamesh assigned

**Comment by Ajil5467** [comment]
I would like to work on this issue.

**Comment by thakran14** [comment]
I would like to work on this issue.

**Comment by thakran14** [comment]
I working on this issue. Please give me a few more days before assigning it to someone else
