### ISSUE TITLE
Remove the CLI and add a Menu

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#111]

**Comment by xandao6** [comment]
This menu should also have a area for programmers input, who prefer to use CLI. For example:
wblast --message spam --times 1000 --target name

**Comment by SinghHimadri** [comment]
Can you please describe this issue in little detail.

**Comment by xandao6** [comment]
It wasn't very well designed, you can have your own idea, but the main idea is to remove the CLI and put a menu like the one we have in session_manager

**Comment by SinghHimadri** [comment]
I would like to work on this issue please assign it to me.

**Comment by xandao6** [comment]
@SinghHimadri assigned

**Comment by rpotter12** [comment]
@xandao6 Please elaborate this idea here. I'm not understanding what is the main purpose of this idea?

**Comment by xandao6** [comment]
@ rpotter12 instead of having to call "wplay -wb target", we can just call "wplay" and then we will have a menu to choose the option, and we can switch from one option to another.

**Comment by rpotter12** [comment]
https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch01s06.html
Please stick to these rules only.
