### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#122]
Implement logging python module, to track the errors easily.

**Comment by navi532** [comment]
Sir, fill me up with more details. i wanna work on it

**Comment by xandao6** [comment]
@navi532  Create a file inside utils named Logger.py and add the following code:
```
import logging
import logging.config
from pathlib import Path

from wplay.utils.helpers import logs_path


class Logger:
    def __init__(self, script_name):
        self.logger = logging.getLogger(script_name)
        self.logger.setLevel(logging.DEBUG)
        Path(logs_path).mkdir(parents=True, exist_ok=True)
        
        if not self.logger.handlers:
            # Create handlers
            file_handler = logging.FileHandler(logs_path/'wplay.log')
            console = logging.StreamHandler()
            file_handler.setLevel(logging.DEBUG)
            console.setLevel(logging.DEBUG)

            # create formatter and add it to the handlers
            formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
            console.setFormatter(formatter)
            file_handler.setFormatter(formatter)

            # add the handlers to logger
            self.logger.addHandler(console)
            self.logger.addHandler(file_handler)

    def debug(self, m):
        self.logger.debug(m)

    def error(self, m):
        self.logger.error(m)

    def info(self, m):
        self.logger.info(m)
```

**Comment by xandao6** [comment]
You can modify the Logger file as you wish. For the future I would like to have a option to activate and deactivate the logger prints in terminal and a config.ini file to choose what logger will print.

# Useful Links
[Python - Logging](https://docs.python.org/3/library/logging.html)
[Real Python - Logging](https://realpython.com/python-logging/)

**Comment by xandao6** [comment]
@navi532 assigned to you, you have 4 days.

**Comment by SinghHimadri** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by xandao6** [comment]
@SinghHimadri  on queue

**Comment by xandao6** [comment]
@navi532 You will be unassigned and added to queue. @SinghHimadri  You will be assigned.

**Comment by SinghHimadri** [comment]
I have done some work wanted to show you just to make sure working in right direction.Shall I make a draft PR?

**Comment by xandao6** [comment]
ok

**Comment by SinghHimadri** [comment]
I have sent a draft pull request please review, suggest changes. I have added a few sample instances please specify the format of the logger and more loggers that I need to add.

**Comment by xandao6** [comment]
@SinghHimadri Hey, just error and info it's ok.  You could save the logs in just one file called logs.log inside a folder logs

**Comment by xandao6** [comment]
@SinghHimadri  could you send your PR? or the issue will be unassigned

**Comment by SinghHimadri** [comment]
I am sending PR, please extend it for a few hours.

**Comment by SinghHimadri** [comment]
@xandao6 @rpotter12 Please have a look at my PR. I guess there are no errors.
