### ISSUE TITLE
Target Search may cause problems in future

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#124]
Currently there is only one method of search targets. 
We will have a big problem if WhatsApp changes, even if small, the selectors or the design.

**Comment by Yash1256** [comment]
@xandao6 I read your project documentation and ya the interesting reason to get the [idea](https://github.com/rpotter12/rpotter12.github.io/blob/master/blogs/blog3-tracking-26-07-2019.md) of this project too I am really excited to work on your project can u guide me in which file I have to work on for solving the issue?

**Comment by xandao6** [comment]
To create more search target methods you will need to modify two files:
1. pyppeteerSearch.py (renamed to target_search.py in the current PR) -> here's our current method.
1. helpers.py ->here are the CSS selectors

To understand the current search method you can run the project and see how it searches.
`wplay -wb any_name`

The current method consists of:
1. Click in 'New Chat'
1. Write the name in the box
1. Get the names filtered (in the current method we were able to differentiate people from groups)
1. When the user select confirm the target in terminal we click in the target.

**Comment by xandao6** [comment]
> @xandao6 I read your project documentation and ya the interesting reason to get the [idea](https://github.com/rpotter12/rpotter12.github.io/blob/master/blogs/blog3-tracking-26-07-2019.md) of this project too I am really excited to work on your project can u guide me in which file I have to work on for solving the issue?

Hi, @Yash1256 .
To create more search target methods you will need to modify two files:
1. pyppeteerSearch.py (renamed to target_search.py in the current PR) -> here's our current method.
1. helpers.py ->here are the CSS selectors

To understand the current search method you can run the project and see how it searches.
`wplay -wb any_name`

The current method consists of:
1. Click in 'New Chat'
1. Write the name in the box
1. Get the names filtered (in the current method we were able to differentiate people from groups)
1. When the user select confirm the target in terminal we click in the target.

**Comment by Yash1256** [comment]
@xandao6 when we type 'wplay -wb any_name' instead of any name if we just type the alphabets then it searches the whole contact list for that alphabet and which word contain that alphabet is shown and by this the list is very  large but terminal shows only 10 contacts and then groups but contacts are even more than 10 (I have checked for my contact list) is this searching process fine ?? Or that Searching which checks for the exact same copy of that name ( ignoring uppercase and lowercase issue ).

**Comment by xandao6** [comment]
The CSS Selector only takes the names that are visible on the screen, so in order to have more contacts we would need to scroll down and do a whole process again. 
But I believe that only 10 is already good, because people look for a specific name. And doing it the other way would make the process very difficult.

**Comment by xandao6** [comment]
@Yash1256 do you wanna work with this issue?

**Comment by Yash1256** [comment]
Sir I am trying to find the issue and solve it but it is taking time. I am working on it but as internal exams are going on so thereby got less time.

**Comment by Yash1256** [comment]
> We will have a big problem if WhatsApp changes, even if small, the selectors or the design.

Sir what exactly we have to do in the target_search.py can u please list down the exact changes to do.

**Comment by Yash1256** [comment]
@xandao6 Sir can u please guide me so that I may proceed further on thus issue.

**Comment by xandao6** [comment]
@Yash1256 I will assign this issue to you. Check out how our current search engine works and create one that looks for targets in another way.

**Comment by xandao6** [comment]
@Yash1256 deadlined extended +4d

**Comment by xandao6** [comment]
@amandhamija98 assigned

**Comment by amandhamija98** [comment]
Hi, I would like to work on this. I'll be making an alternate search method by using the normal search option for contacts, not the new chat button

**Comment by xandao6** [comment]
@amandhamija98  assigned, @Yash1256 added to queue

**Comment by amandhamija98** [comment]
I have submitted a pull request: https://github.com/rpotter12/whatsapp-play/pull/224
Kindly let me know if it is ok

**Comment by rpotter12** [comment]
@amandhamija98 Thanks :)
