### ISSUE TITLE
GitHub releases?

### ISSUE THREAD

**Issue by nileshpatra** [rpotter12/whatsapp-play#125]
There are several changes, it would be a good idea to do releases every once in a while.
However there are major bumps in releases 
3 -> 5, 
2.2 -> 3

Why is that?
I would suggest doing point releases 
For example : 2 -> 2.1

Bumping releases directly by 2 doesn't look like a great idea.

**Comment by rpotter12** [comment]
@nileshpatra Release changes were done in a systematic manner in setup.py file. 
At that time I was busy with some college stuffs. So I was not able to see the repository at that time. That's why some release left.
