### ISSUE TITLE
Add a option to manually choose the target!

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#130]
Actually we use a script to search the target, why not let the user go to the whatsapp and manually choose the target?

**Comment by poojasahu10** [comment]
@xandao6 : I want to clarify one point - Do we need to suggest for target from the contact list or just the the list of recently used targets in the whatsapp launch page ?

**Comment by poojasahu10** [comment]
@xandao6 : I am interested to work on this issue. kindly assign it to me. Thanks.

**Comment by xandao6** [comment]
@poojasahu10 just pause the program, let the person choose the target, then the program identify the target choosed and start

**Comment by poojasahu10** [comment]
@xandao6 : From the pyppeteer module : I found that if waited for the selector whatsapp_selectors_dict['target_focused_title'] and whatsapp_selectors_dict['message_area'] our use case can be solved. Kindly let me know if I am missing any edge case or I will continue to raise a pull request. Thanks.

**Comment by xandao6** [comment]
@poojasahu10 Yes, that's a good idea. Before that print out for the person to choose the target. And after the person chooses, we need to ask the person to confirm the target.

**Comment by poojasahu10** [comment]
@xandao6 @rpotter12 :  I have raised PR [link](https://github.com/rpotter12/whatsapp-play/pull/184) for this issue. Its failing for circleci tests, I would like to know more about it. Kindly review the same .

**Comment by xandao6** [comment]
CircleCI isn't well configured
