### ISSUE TITLE
 Add an option to target a specific number, without the need to include in your phonebook

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#133]
![image](https://user-images.githubusercontent.com/22106326/75196888-a881fe80-573b-11ea-805b-eb82a7a50a3b.png)

**Comment by SubhradeepSS** [comment]
@xandao6 @rpotter12 I would like to work on this issue.
Can you please help a bit about how to begin?

**Comment by xandao6** [comment]
You need to detect when users write a number instead a string, then you need to open a new page with the url: wa.me/_number_.

**Comment by xandao6** [comment]
You need to work with browser_config.py and little with target_search.py

**Comment by SubhradeepSS** [comment]
@xandao6 can u please extend the deadline for the completion of the issue?

**Comment by xandao6** [comment]
Extended +4d

**Comment by SubhradeepSS** [comment]
> 
> 
> You need to work with browser_config.py and little with target_search.py

Can you explain a bit more as I have not worked on web,therefore facing difficulty?

**Comment by xandao6** [comment]
what is the problem?

**Comment by xandao6** [comment]
user write a number instead a string -> make this differentiation with logic
When its number you need to create a new tab, there is a function to do that in browser_config
Then you need to load the url: wa.me/number, also there is a function in browser_config
Wait the page to load and it's done.

All this logic above you can put in target_search

**Comment by xandao6** [comment]
how is it going?

**Comment by Rits1272** [comment]
May I work on this issue @xandao6 @rpotter12?
