### ISSUE TITLE
whatsapp-play is not tracking the name having emoticons 

### ISSUE THREAD

**Issue by csharp489** [rpotter12/whatsapp-play#139]
**Expected Behaviour**
Able to track the name having emoticons like(Anyname1 ❤ OR ❤AnyName2❤).
It should execute the command `wplay -wt "Anyname"`. 
**Actual behaviour**
![e](https://user-images.githubusercontent.com/42842260/75511807-554acd00-5a15-11ea-823a-7df18fb58dc0.PNG)
On Analysing this unexpected output I found there is some UnicodeEncodeError.
**Specifications**
OS: Window 10
platform: window Terminal( window powershell)

**Comment by xandao6** [comment]
@csharp489  Have you tried a name without any emoji?

**Comment by csharp489** [comment]
Yes,I have tried. The command is working fine without using emoji.

**Comment by xandao6** [comment]
I don't know if this error happens to more people, it doesn't happen to me. It will be necessary to debug, find the problem and deal with the error.

**Comment by csharp489** [comment]
I guess there is some UTF error. I found that Unicode" on Windows is UTF-16LE, and each character is 2 or 4 bytes. Linux uses UTF-8, and each character is between 1 and 4 bytes.

**Comment by xandao6** [comment]
@csharp489 do you wanna work with this issue?

**Comment by csharp489** [comment]
Yes, I want to work on this issue.

**Comment by Yash1256** [comment]
@csharp489 It is working fine with the emoji,
![Yash1256](https://user-images.githubusercontent.com/56587507/75805261-81fd3c80-5da7-11ea-89ab-c4349f795f1a.png)

**Comment by xandao6** [comment]
It doesn't happen for everyone.

**Comment by Yash1256** [comment]
@xandao6 the search pattern which we are following is not dependent on the platform as I know, I have done the same in mac and for ubuntu I didn't encounter any error but if it is happening in windows can u explain me what's the reason of happening of this?

**Comment by xandao6** [comment]
I don't know, it's an error with decoding the emoji. The error also doesn't happen with me in windows 10.

**Comment by csharp489** [comment]
But why I am facing this issue .May be some access is denied in my system. Please tell me what i have to do now? @xandao6 
Do I need to proceed with the same or need to workout on other issue.

**Comment by xandao6** [comment]
If you're able to solve then solve, if not look for another issue.

**Comment by csharp489** [comment]
@Yash1256 @xandao6  can u please check all these Given example as test cases.
😋Any_Name😋
🙄Any🙄Name😊
🤣Any🤣2🤣Name🤣

Please check all these test cases. Meanwhile I am looking for another issue.

**Comment by xandao6** [comment]
working..
