### ISSUE TITLE
separate Contributing Guidelines

### ISSUE THREAD

**Issue by Bhupesh-V** [rpotter12/whatsapp-play#142]
It would be nice to unclutter the README and separate contributing guidelines in a separate `CONTRIBUTING.md` file.

Basic format may look like

# Contributing to whatsapp-play

:+1::tada: First off, thanks for taking the time to contribute! :tada::+1:

Make sure you follow below guidelines before contributing.

1. Raise an issue before sending any PR.
2. Make you changes to `feature` branch.
3. See if there is already an open PR for the same issue.

**Comment by Antaripa** [comment]
I would like to work on this issue.

**Comment by SinghHimadri** [comment]
I would like to work on this issue. Can this issue be assigned to me?

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by priyansh19** [comment]
I would like to work on this Issue 
Already added a file in my PR : https://github.com/priyansh19/whatsapp-play/blob/master/CONTRIBUTION.md

**Comment by xandao6** [comment]
This issue will be closed

**Comment by xandao6** [comment]
@Antaripa  You need to open a PR to our master branch! You has merged it into your own repository.

**Comment by xandao6** [comment]
@priyansh19 After we merge her PR you can edit it.

**Comment by priyansh19** [comment]
Assign this task to me I will edit it @xandao6

**Comment by priyansh19** [comment]
Added Basic Contribution guidelines 
will update it soon with few more additions :)
