### ISSUE TITLE
Type Annotation

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#143]
Add Type Annotations in all code to be more readable. Be careful not to use specific versions above python 3.6, because this is the minimum version of our project and many people use it.
https://docs.python.org/3.6/library/typing.html

**Comment by shvamabps** [comment]
I have 3.6.9

**Comment by xandao6** [comment]
I meant not to use specific python 3.7+ things

**Comment by preeti13456** [comment]
Interested

**Comment by xandao6** [comment]
@preeti13456  assigned

**Comment by preeti13456** [comment]
Type Annotations
1. src < onlinetracker.png >
![onlinetracker](https://user-images.githubusercontent.com/36129347/75775904-f10f6c80-5d78-11ea-929f-93bc503ecc24.png)

2. src <messagetime.png>
![messagetimer](https://user-images.githubusercontent.com/36129347/75776111-59f6e480-5d79-11ea-8d30-6a5cb1649a2f.png)

3. src < tgbot.py >
![tgbot py](https://user-images.githubusercontent.com/36129347/75776564-3a13f080-5d7a-11ea-8c03-b81c2e474150.png)

**Comment by xandao6** [comment]
Looks good, send your PR when you finish

**Comment by xandao6** [comment]
@preeti13456 deadlined extended +4d. Send your PR please.

**Comment by preeti13456** [comment]
Thanks will do asap

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xandao6** [comment]
@preeti13456 can you send your PR again with the changes?

**Comment by SinghHimadri** [comment]
Is this issue completed or I would like to work on this.
