### ISSUE TITLE
Get full info about one target (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#144]
If is a person:
- person name
- about
- number
- groups in common 
- profile photo

If is a group:
- group name
- how many people
- group profile
- description
- participant's names
- _participant's numbers ? -> this part is difficult and can be postponed_

**Comment by amandhamija98** [comment]
I would like to work on this issue, I will start by getting name, about, number and groups in common

**Comment by xandao6** [comment]
okay, get the person profile photo too

**Comment by amandhamija98** [comment]
ok, I will try that

**Comment by xandao6** [comment]
@amandhamija98  you can do just the person part and let the group part for another person.  Also the issue #83 was closed.

**Comment by amandhamija98** [comment]
Sure, thankyou

**Comment by amandhamija98** [comment]
Could you please assign this issue to me

**Comment by xandao6** [comment]
One more person could be assigned to this issue, to do the group part.

**Comment by preeti13456** [comment]
Interested

**Comment by xandao6** [comment]
@preeti13456 what part do you want to do? if it is for "person" you have to enter the queue.

**Comment by preeti13456** [comment]
Sure

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by amandhamija98** [comment]
Hi, I am facing a slight hiccup while resolving this issue and it's taking longer than I expected. Could I please get two more days

**Comment by xandao6** [comment]
@preeti13456 you can accept or reject the comment above

**Comment by preeti13456** [comment]
Accept

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by preeti13456** [comment]
Almost think about what has to be done but due to the recent changes facing some problems .

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xandao6** [comment]
@amandhamija98 You will be unassigned at day 8.

**Comment by amandhamija98** [comment]
I've submitted a pull request
