### ISSUE TITLE
BEGINNERS: Install the software and execute the tracking command successfully

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#145]
###GSSOC 2020 
1. Read the README.md file of the project.
2. Participant have successfully install the software.
3. have to run tracking command successfully.
4. Open a pull request adding screenshots of successfully installed software and executing tracking command in screenshot folder.

Tracking guide: https://github.com/rpotter12/whatsapp-play/wiki/Usage#whatsapp-track

**Comment by csharp489** [comment]
please Add some demo(example) about how to execute the command for tracking ,messaging, chatting and all in documentation .
-wt: wplay -wt "anyName" please give the example for all the arguments.

**Comment by ranjal007** [comment]
I would like to work on this issue 
please assign it to me for gssoc20.

**Comment by rpotter12** [comment]
This is an open issue.

**Comment by xandao6** [comment]
If you do this you will earn GSSoC points, it's for everyone!

**Comment by csharp489** [comment]
Yes,I will also do this .

**Comment by viduu** [comment]
#145 @xandao6 
![Screenshot (1)](https://user-images.githubusercontent.com/52102657/75621288-0735e680-5b47-11ea-98cc-43eb8cc218b9.png)
![Screenshot (2)](https://user-images.githubusercontent.com/52102657/75621294-174dc600-5b47-11ea-89b1-2d0b298f53f6.png)
succesfully installed...

**Comment by viduu** [comment]
@xandao6 
![Screenshot (3)](https://user-images.githubusercontent.com/52102657/75621382-66e0c180-5b48-11ea-87b3-e29135fa643c.png)
![Screenshot (2)](https://user-images.githubusercontent.com/52102657/75621385-73fdb080-5b48-11ea-9626-a38a598336b4.png)
sucessfully installed.....

**Comment by Yash1256** [comment]
![Screenshot from 2020-03-01 12-15-08](https://user-images.githubusercontent.com/56587507/75621495-15254f00-5bbb-11ea-90b7-d98d3764fe8a.png)
![Screenshot from 2020-03-01 12-09-18](https://user-images.githubusercontent.com/56587507/75621499-18203f80-5bbb-11ea-8041-ebcfe3a8094c.png)
@xandao6 Successfully Installed and executed tracking command.
I have also opened a PR but it is showing some error so placed here.

**Comment by viduu** [comment]
> ![Screenshot from 2020-03-01 12-15-08](https://user-images.githubusercontent.com/56587507/75621495-15254f00-5bbb-11ea-90b7-d98d3764fe8a.png)
> ![Screenshot from 2020-03-01 12-09-18](https://user-images.githubusercontent.com/56587507/75621499-18203f80-5bbb-11ea-8041-ebcfe3a8094c.png)
> @xandao6 Successfully Installed and executed tracking command.
> I have also opened a PR but it is showing some error so placed here.
@Yash1256 which error?

**Comment by viduu** [comment]
@Yash1256 which error?

**Comment by preeti13456** [comment]
Interested

**Comment by vineetjk** [comment]
![screenshot-wplay](https://user-images.githubusercontent.com/42497152/75627510-da410c80-5bf6-11ea-8cd6-64dcc76cb0af.png)

**Comment by mySTRiouscoder** [comment]
![image004](https://user-images.githubusercontent.com/56103228/75628629-efbb3400-5c00-11ea-9c79-d3e290cec607.jpg)
![image001](https://user-images.githubusercontent.com/56103228/75628634-01044080-5c01-11ea-8d32-e586d1d434b6.png)

**Comment by 07ATUL** [comment]
@xandao6 I would like to work on this issue

**Comment by 07ATUL** [comment]
![status](https://user-images.githubusercontent.com/32452535/75631674-f6ef3b80-5c1a-11ea-8a1c-4d502749db22.PNG)

**Comment by xandao6** [comment]
**Everyone can work with this issue, just send a PR.**

**Comment by Neelaksh-Singh** [comment]
SUCCESSFULLY installed and executed



[Beginners.docx](https://github.com/rpotter12/whatsapp-play/files/4274130/Beginners.docx)

**Comment by preeti13456** [comment]
Successfully compiled and Executed
![wplay imp](https://user-images.githubusercontent.com/36129347/75689152-b947ec80-5cc6-11ea-8c4b-fed129c1d2d3.png)

**Comment by NikhileshKatakam** [comment]
SUCCESSFULLY installed and executed
![k nikhilesh software installed](https://user-images.githubusercontent.com/55126546/75698522-e3081000-5cd4-11ea-81be-58b29950b62e.png)
![k nikhilesh tracking command](https://user-images.githubusercontent.com/55126546/75698525-e4393d00-5cd4-11ea-8d9f-7ba88dcfc8a1.png)

**Comment by Neelaksh-Singh** [comment]
These are the screenshots for successful installation of wplay.
Also one can see the tracker feature in action.
![image](https://user-images.githubusercontent.com/56018436/75768290-1648ae80-5d6a-11ea-87b8-d5fb935f88a6.png)
![image](https://user-images.githubusercontent.com/56018436/75768341-2791bb00-5d6a-11ea-9fab-adbbcf078b07.png)

![image](https://user-images.githubusercontent.com/56018436/75768356-2fe9f600-5d6a-11ea-8968-2cd76ad46fc1.png)

**Comment by rpotter12** [comment]
@preeti13456 @Neelaksh-Singh @07ATUL Add execution screenshot in the screenshot folder, commit them and open a PR of it. :)

**Comment by anmolkaur18** [comment]
<img width="672" alt="wplay1" src="https://user-images.githubusercontent.com/53399726/75779374-58440700-5d0e-11ea-8ebe-7747ee153767.png">

<img width="944" alt="wplay2" src="https://user-images.githubusercontent.com/53399726/75779403-6560f600-5d0e-11ea-84c3-bbfd27da793b.png">

<img width="526" alt="wplay5" src="https://user-images.githubusercontent.com/53399726/75779417-6c880400-5d0e-11ea-9bae-421e2c32f409.png">

**Comment by rpotter12** [comment]
Read the above comment(https://github.com/rpotter12/whatsapp-play/issues/145#issuecomment-593943941)

**Comment by rpotter12** [comment]
@Yash1256 read the comment(https://github.com/rpotter12/whatsapp-play/issues/145#issuecomment-593943941)

**Comment by Yash1256** [comment]
@rpotter12 Now what we have to do more in this sir??

**Comment by anmolkaur18** [comment]
@rpotter12 sir please check I have made a pull request.

**Comment by SinghHimadri** [comment]
@rpotter12 Please have a look at my PR. I guess there are no errors.

**Comment by rpotter12** [comment]
> @rpotter12 Now what we have to do more in this sir??

@Yash1256 please read the first comment. That comment specifies what you have to do in this issue. :)

**Comment by BhanujaAggarwal** [comment]
Installation Done !
@xandao6 @rpotter12 look at my PR

**Comment by BhanujaAggarwal** [comment]
![BhanujaAggarwal](https://user-images.githubusercontent.com/33261795/76108069-e61a3d80-5fff-11ea-9137-e2e7add6befd.png)

**Comment by brainaxe123** [comment]
![installed_brainaxe123](https://user-images.githubusercontent.com/48864918/76140644-bbbd9400-6082-11ea-9cce-6aa2d42cb7dd.JPG)
![tracking_command_brainaxe123](https://user-images.githubusercontent.com/48864918/76140647-bf511b00-6082-11ea-84ae-1a3438968161.JPG)

**Comment by Neelaksh-Singh** [comment]
Installed the software successfully .
![image](https://user-images.githubusercontent.com/56018436/76163025-da965600-6168-11ea-8824-36f5497eecdb.png)

![image](https://user-images.githubusercontent.com/56018436/76163038-e550eb00-6168-11ea-8e36-064f53754f8a.png)
![image](https://user-images.githubusercontent.com/56018436/76163048-f8fc5180-6168-11ea-959f-6aad30916e38.png)

**Comment by SwaraliDinkar** [comment]
Successfully installed!
![Screenshot from 2020-03-08 17-58-23](https://user-images.githubusercontent.com/43184066/76163327-1cc09700-616b-11ea-92b0-918ae40eb47e.png)

**Comment by rpotter12** [comment]
@SwaraliDinkar You have you add your screenshot in screenshots folder and then create a PR for it.

**Comment by thakran14** [comment]
kindly assign this issue to me.

**Comment by shreyakapoor08** [comment]
Can i take up this issue?

**Comment by 19isha98** [comment]
![wplay_run](https://user-images.githubusercontent.com/42314217/76675733-71886580-65e2-11ea-98b5-acb4f87f50b2.jpg)

**Comment by 19isha98** [comment]
I have uploaded a screenshot of successful execution in my system

**Comment by Meenakshi2000** [comment]
Can I too do this one?

**Comment by zulkernine** [comment]
> If you do this you will earn GSSoC points, it's for everyone!

Plz assign me this issue.

**Comment by zulkernine** [comment]
![Screenshot from 2020-03-16 11-46-49](https://user-images.githubusercontent.com/53091788/76728152-eb078b80-677b-11ea-924a-9f6f471f0e02.png)


I'm getting some error here , please help

**Comment by rpotter12** [comment]
@shreyakapoor08 @19isha98 @zulkernine @Meenakshi2000 Go ahead in solving this beginners issue.

**Comment by Meenakshi2000** [comment]
Thank you for your response , I will surely work on it

**Comment by kichloo** [comment]
@xandao6 Made the PR.

**Comment by meghanagottapu** [comment]
@rpotter12 I made a pull request

**Comment by sanujana045** [comment]
How to upload the screenshot and made the pull request...? anyone help me please.!

**Comment by rpotter12** [comment]
> Where to upload the screenshot and how to made the pull request...? anyone help me please.!

@sanujana045 Please read the starting comment of the issue :)

**Comment by rpotter12** [comment]
> @xandao6 Made the PR.

@kichloo Read the comment in the PR

**Comment by saks1209am** [comment]
![wplay1](https://user-images.githubusercontent.com/30996074/77528307-b13d3000-6eb3-11ea-84a8-1eb3a33dcdfc.jpg)
I'm getting this error after running the tracking command

**Comment by xandao6** [comment]
Update your fork or clone.

**Comment by sim12cool** [comment]
I have created a pull request for this issue.Uploaded all the required screenshots.

**Comment by rajraman786** [comment]
> 
> 
> **Everyone can work with this issue, just send a PR.**

sir, 
   please assign me.
  i want to work on this.

**Comment by rajraman786** [comment]
@rpotter12 
may i work on this?

**Comment by rpotter12** [comment]
> @rpotter12
> may i work on this?

sure @rajraman786. Start working on it. :)

**Comment by shreyakapoor08** [comment]
@rpotter12 I have raised the PR. Kindly check.
![image](https://user-images.githubusercontent.com/31164665/79670229-1c420400-81df-11ea-9dde-0e2932672a5a.png)

**Comment by 97shivank** [comment]
![error](https://user-images.githubusercontent.com/31972312/79681242-4c68c180-8236-11ea-9a9f-4c926682646a.png)
I'm getting this error

**Comment by 97shivank** [comment]
![error](https://user-images.githubusercontent.com/31972312/79681423-d9f8e100-8237-11ea-93e7-a3e2e421eb46.png)
i'm getting this error.

**Comment by sanujana045** [comment]
![WhatsApp Image 2020-04-19 at 01 06 11](https://user-images.githubusercontent.com/61049118/79683710-7d062680-8249-11ea-883a-17c44eb7482c.jpeg)
![WhatsApp Image 2020-04-19 at 01 06 08](https://user-images.githubusercontent.com/61049118/79683718-868f8e80-8249-11ea-807f-ce725ad2fe0a.jpeg)
#307 #153 
@rpotter12 I have created the pull request..please check it.

**Comment by rpotter12** [comment]
> ![error](https://user-images.githubusercontent.com/31972312/79681423-d9f8e100-8237-11ea-93e7-a3e2e421eb46.png)
> i'm getting this error.

Ignore this

**Comment by 97shivank** [comment]
![shivank_tracking](https://user-images.githubusercontent.com/31972312/79686580-1db31100-825f-11ea-8e3b-042d4afd75a3.png)
@rpotter12 I have raised a PR. Kindly check it.

**Comment by vipuldcoder** [comment]
I am interested working on this issue, Can anyone please do assign me?

**Comment by Ritacheta** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/60181987/80019619-74397d00-84f5-11ea-91f1-fb8704a1bde3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/60181987/80019626-78fe3100-84f5-11ea-96dc-9e4bfdffaa45.png)
done with installation. I want to contribute. Can anyone please do assign me??

**Comment by rpotter12** [comment]
@Ritacheta create a PULL REQUEST

**Comment by Ritacheta** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/64324128/80287701-67fd2c00-8750-11ea-99a1-eb640d22a49a.png)
![Screenshot (5)](https://user-images.githubusercontent.com/64324128/80287704-6af81c80-8750-11ea-8069-6c5b3550ea13.png)
please assign me

**Comment by vaquersame** [comment]
Hi there.
![Captura](https://user-images.githubusercontent.com/55640630/80292147-a62b2900-8719-11ea-9a56-395b77175563.jpg)
![Captura_2](https://user-images.githubusercontent.com/55640630/80292148-acb9a080-8719-11ea-9314-28ba813b717c.JPG)

 I want to contribute. Can anyone please do assign me?

**Comment by rpotter12** [comment]
@vaquersame no need to get assigned in this issue. Start doing this task. :)

**Comment by arpitasahakundu** [comment]
can ido the task now

**Comment by Satyam3976** [comment]
![satyam](https://user-images.githubusercontent.com/25302027/80709902-c25d0a80-8b0b-11ea-8aa7-679df0904549.jpg)

**Comment by AnkitaBIT** [comment]
<img width="960" alt="wplay1" src="https://user-images.githubusercontent.com/44089458/81902117-39e76b00-95dd-11ea-85eb-5cb913e09bab.PNG">
What issue am I facing? Can you please help @rpotter12

**Comment by rpotter12** [comment]
> <img alt="wplay1" width="960" src="https://user-images.githubusercontent.com/44089458/81902117-39e76b00-95dd-11ea-85eb-5cb913e09bab.PNG">
> 
> What issue am I facing? Can you please help @rpotter12

It is a timeout error. Reinstall the software and test it again. :)

**Comment by Rukmini-Meda** [comment]
Can I work on this for GSSoC20?
