### ISSUE TITLE
Find out whether there is a specific contact name in your friend's contact list

### ISSUE THREAD

**Issue by sim12cool** [rpotter12/whatsapp-play#148]

**Comment by xandao6** [comment]
How? Can you explain more?

**Comment by preeti13456** [comment]
Interested

**Comment by xandao6** [comment]
From what I understand, this cannot be possible, I am waiting for him to give more details.

**Comment by NikhileshKatakam** [comment]
Intrested sir

**Comment by rpotter12** [comment]
@sim12cool Please explain your whole idea here. :)
