### ISSUE TITLE
Refactore session manager and remove recursion

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#149]
Currently, the menu uses recursion to restart itself, it is not good practice.

## How to do?
In the file session_manager.py we need to remove all recursion and intead add a State Machine.

## Helpful links
https://python-3-patterns-idioms-test.readthedocs.io/en/latest/StateMachine.html
https://dev.to/karn/building-a-simple-state-machine-in-python

## Questions
Why not just add a loop in session manager? Because the menu will be much more complex in the next implementation that is being planned (headless mode)

**Comment by charan7386** [comment]
I am interested in solving this, please assign it ti me.

**Comment by xandao6** [comment]
@charan7386 assigned

**Comment by preeti13456** [comment]
Interested

**Comment by xandao6** [comment]
@preeti13456 are you on the line.

**Comment by preeti13456** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
