### ISSUE TITLE
onlinetracker for multiple users (Idea)

### ISSUE THREAD

**Issue by Rantun** [rpotter12/whatsapp-play#15]
Hi, its possible use the wt option to register more than one account?, the idea is to have a register for instance 10 contacts.

Thanks

Reblanc

**Comment by rpotter12** [comment]
Hi @Rantun 
1. Please write your idea in the README.md file and create a pull request for that changes.
2. And then start implementing your idea.

Cheers🤟🏻

**Comment by rpotter12** [comment]
#61 is also same as this issue

**Comment by jd2053742-lgtm** [comment]
Hola
