### ISSUE TITLE
The updater code for telegram bot

### ISSUE THREAD

**Issue by shvamabps** [rpotter12/whatsapp-play#154]
possibly It is the token for telegram bot that is required for the -wtb to work on
So what one can do is that either they can put the token already for the bot to work on
else the option is of cli
here the code for updater is showing deprecated
maybe one need to recode the whole code of update or part of the code can have some changes
It might be insecure for the user to insert the token number at run time

**Comment by csharp489** [comment]
For Window user:
If someone want token to run that command then He/she can go to the link given below:
https://www.siteguarding.com/en/how-to-get-telegram-bot-api-token
By using the process given in the blog ,you can access your token But remember never share it with anyone. Otherwise It can be used by anyone to control your bot.

**Comment by rpotter12** [comment]
@shvamabps everyone has his/her own telegram-bot token. The idea of -wtb was to enter the token everytime whenever we run that command.

**Comment by shvamabps** [comment]
In that case the user has to always keep his token with himself. It may be annoying not at once but when done multiple time.

**Comment by rpotter12** [comment]
@shvamabps we can do that once user enter the token, it will update that token value and then whenever we run -wtb command the software will not need to enter token every time, but remember software should always ask for token because if a user want to enter a new token then that option will help.

**Comment by shvamabps** [comment]
@rpotter12  we can provide that option too 
If the user want to change the token / add a new one.

**Comment by xandao6** [comment]
@shvamabps how is it going?

**Comment by chttrjeankr** [comment]
Would you want some help on this one? @xandao6 @rpotter12 

My approach will be to save the TOKEN once entered into a local pickle file and load from it the next time the user wants to access the bot. The user will be prompted each time on whether they want to use the existing token or reenter the TOKEN.

**Comment by xandao6** [comment]
You can work on this @chttrjeankr
