### ISSUE TITLE
Proper documentation of codes is required in the various python scripts to know about where the control of the program is going.

### ISSUE THREAD

**Issue by 07ATUL** [rpotter12/whatsapp-play#167]
@rpotter12 what do you think? if  yes can i work on it?

**Comment by xandao6** [comment]
Sure, assigned.

**Comment by xandao6** [comment]
@07ATUL deadline extended +4d

**Comment by 07ATUL** [comment]
Thanks

**Comment by Castella1313** [comment]
Can this issue be assigned to me?

**Comment by xandao6** [comment]
@Castella1313  added to queue

**Comment by SwaraliDinkar** [comment]
I want to work on this issue.Please assign!

**Comment by xandao6** [comment]
@SwaraliDinkar added to queue

**Comment by suubh** [comment]
Assign this issue to me .
