### ISSUE TITLE
pyppeteer.TimeoutError: timeout exceeds 30000ms exceeds

### ISSUE THREAD

**Issue by kancherlakishorereddy** [rpotter12/whatsapp-play#183]
I've forked and cloned the repo recently and on running the "__main__.py" file, for wchat, WhatsApp web opens in chromium and selects the search bar, but the target name doesn't go into the search bar neither does the target chat page opens and a few seconds later the browser closes, then the process gets killed and shows the timeout error.
![Screenshot from 2020-03-04 13-21-44](https://user-images.githubusercontent.com/49707819/75860103-4a32db00-5e21-11ea-9e62-af21a97b40c1.png)

**Comment by Yash1256** [comment]
The same functionality is happening with me 
I have also tried `wplay -wt "any_name"` it is not showing in that command even to.

**Comment by xandao6** [comment]
some selectors was changed, they need to be updated.

**Comment by xandao6** [comment]
#187
