### ISSUE TITLE
Recommendation System for Whatsapp-play (Idea)

### ISSUE THREAD

**Issue by Ratna04priya** [rpotter12/whatsapp-play#186]
I would like to add a recommendation system for WhatsApp-play. This could be done by using machine learning, analysing the previous data of the user on the basis of what they write or could write.  That would be very helpful for the user to write, or can be used for spelling mistakes.

**Comment by ayushbathrey** [comment]
I wouldn't call it a recommendation system, but a quick reply feature.

**Comment by Ratna04priya** [comment]
Yeah, but it can recommend as well... works by the same fact!

**Comment by rpotter12** [comment]
@Ratna04priya I don't think this will be a good idea to implement recommendation system in this project for now. We can keep this idea for the future scope. :)
