### ISSUE TITLE
Selectors changed

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#187]
Apparently there were some changes on the whatsapp web site and some selectors have changed, I need you to check all the selectors located in the helpers file.

**Comment by amandhamija98** [comment]
Can I be assigned this please

**Comment by rpotter12** [comment]
@xandao6 I suggest you should solve this issue asap. Because our software mainly depends on this. :)

**Comment by amandhamija98** [comment]
Ok, I'll check this tonight

**Comment by amandhamija98** [comment]
This is the selector that has been changed :  'search_contact_input_new_chat': '#app > div > div span > div > span > div > div > div > label > div > div:last-of-type',
Haven't checked the others but I think they're the same

**Comment by xandao6** [comment]
Ok
