### ISSUE TITLE
Adding New Workflows for faster reply and reviews of code

### ISSUE THREAD

**Issue by priyansh19** [rpotter12/whatsapp-play#188]
It includes:
- Leaving a comment on a new PR.
- Adding new Continous Integration Tool
- Adding new PR review tool

**Comment by priyansh19** [comment]
I will Like to work on this issue

**Comment by priyansh19** [comment]
please assign it to me :)

**Comment by xandao6** [comment]
This was done @priyansh19 @rpotter12 ?

**Comment by priyansh19** [comment]
Yes .. it's done

**Comment by priyansh19** [comment]
I have created a PR a week back .. adding Greetings.yml , Stale.yml , Labeler.yml

**Comment by rpotter12** [comment]
Why does they fails every time??

**Comment by priyansh19** [comment]
@rpotter12 check them in GitHub actions.. they have several restrictions
when participants doesn't follow them they fails
Not every time they fails ..

**Comment by priyansh19** [comment]
It need a little bit of modification .. I do it Soon
