### ISSUE TITLE
.travis.yml and codecov script for testing

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#20]
.travis.yml script for travis check

**Comment by aryangulati** [comment]
Can u explain a bit about issue?

**Comment by xandao6** [comment]
https://codecov.io/

**Comment by manaswitatyagi** [comment]
Is the issue still active? I am really interested in taking it up.

**Comment by xandao6** [comment]
@manaswitatyagi assigned

**Comment by xandao6** [comment]
@manaswitatyagi any news?

**Comment by SinghHimadri** [comment]
I would like to work on this issue please assign it to me.
