### ISSUE TITLE
chromium isn´t starting

### ISSUE THREAD

**Issue by dogexan** [rpotter12/whatsapp-play#204]
The installation was successful. (v6.0.0)

Then I tried to use the tracking comand `python3 -m wplay -wc "test"` and got the following result:

![wPlay-chromium-bug](https://user-images.githubusercontent.com/56969158/76209618-8e97ef80-6202-11ea-89e1-4e89dfaedcc9.PNG)

There are no Chromium windows appearing (QR Code or anything else)

**Comment by HarsheetKakar** [comment]
tried downloading chromium separately?

**Comment by dogexan** [comment]
After the automatic installation by wplay, chromium ist installed under:
C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pyppeteer\pyppeteer\local-chromium\575458\chrome-win32

![chrome-path](https://user-images.githubusercontent.com/56969158/76226024-944efe80-621d-11ea-8970-77cf4b9c0432.PNG)

I tried to start the "chrome.exe" manually. But I got this:
![chromium-start](https://user-images.githubusercontent.com/56969158/76226309-fad41c80-621d-11ea-8613-0a14563aa95e.PNG)

When I copy the whole folder "chrome-win32" to my deskop, I´m able to start chromium as usual.

Also, I tried to replace the automatically installed Chromium by a self downloaded Version (82.0.4082.0) with the same result.

**Comment by HarsheetKakar** [comment]
can you please translate the error in powershell? and give the complete error information given in the chromium tab?

**Comment by dogexan** [comment]
Translation of powershell output:
"This application could not be started because the side-by-side configuration is incorrect. For more information, see the application event log. Further details can also be viewed with the command line tool sxstrace.exe"

![Ereignisanzeige](https://user-images.githubusercontent.com/56969158/76230882-ab451f00-6224-11ea-9be3-5c1c4b0009e9.PNG)

Error generating the activation context for "C:\Users\alexa\AppData\Local\pyppeteer\pyppeteer\local-chromium\575458\chrome-win32\chrome.exe". The dependent assembly "69.0.3494.0,language="&#x2a;",type="win32",version="69.0.3494.0"" could not be found. Use the program "sxstrace.exe" for a detailed diagnosis.

I´m not sure how to use the "sxstrace.exe" tool

The chromium Tab says only:
"Error while displaying this website"


"Normal" web pages can also not be displayed (only under this path "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pyppeteer\pyppeteer\local-chromium\575458\chrome-win32") 

In an other folder like my dektop, I can start chromium without errors.

**Comment by HarsheetKakar** [comment]
try opening chromium as admin, if it works then change folder privileges.

**Comment by dogexan** [comment]
Run as admin doesn't change anything.

Can I change the installation path of chromium in "wplay"?

I have the same problems with an other Windows 10 PC too.

**Comment by xandao6** [comment]
32 bits or 64 bits? doesn't work with 32 bits

**Comment by priyansh19** [comment]
Your Computer architecture is based on 32bit architecture as in screenshots

**Comment by priyansh19** [comment]
So wplay won't work on it

**Comment by priyansh19** [comment]
@xandao6 @rpotter12 please close this issue

**Comment by dogexan** [comment]
Sorry for the late reply.

I have a 64bit System. I tried chromium 64bit and 32bit without success.
![systeminfo](https://user-images.githubusercontent.com/56969158/77246253-c43ad080-6c25-11ea-8efe-131990de856a.png)

![systeminfo2](https://user-images.githubusercontent.com/56969158/77246272-efbdbb00-6c25-11ea-9065-03957dedc1ac.png)

**Comment by xandao6** [comment]
@dogexan  How you are installing wplay?

**Comment by rpotter12** [comment]
@dogexan I don't know the exact problem but it might be similar to https://sichernpc.de/fragt-uns/wie-behebt-man-in-windows-den-fehler-die-anwendung-konnte-nicht-korrekt-gestartet-werden-0xc000007b/

**Comment by dogexan** [comment]
@xandao6 
I installed python 3.8 via Microsoft Store (I also tired python 3.7)

Open Powershell --> 

`PS C:\Users\alexa> python -m pip install wplay                                                                                                                                                                                               Collecting wplay
  Using cached https://files.pythonhosted.org/packages/43/6e/17811961dbe682656f74c1e046bcf07134c077053909bc2028aca53c5c10/wplay-7.0.0-py3-none-any.whl
Collecting python-telegram-bot>=11.1.0 (from wplay)
  Using cached https://files.pythonhosted.org/packages/16/5f/ab10cfacd6dba5deb7b7c3a78ddb23ae4404d6c6eb8b3c3e121668d4bf94/python_telegram_bot-12.4.2-py2.py3-none-any.whl
Collecting pyppeteer>=0.0.25 (from wplay)
  Using cached https://files.pythonhosted.org/packages/b0/16/a5e8d617994cac605f972523bb25f12e3ff9c30baee29b4a9c50467229d9/pyppeteer-0.0.25.tar.gz
Collecting datetime>=4.3 (from wplay)
  Using cached https://files.pythonhosted.org/packages/73/22/a5297f3a1f92468cc737f8ce7ba6e5f245fcfafeae810ba37bd1039ea01c/DateTime-4.3-py2.py3-none-any.whl
Collecting psutil>=5.7.0 (from wplay)
  Using cached https://files.pythonhosted.org/packages/86/fe/9f1d1f8c1c8138d42fc0e7c06ca5004e01f38e86e61342374d8e0fa919e4/psutil-5.7.0-cp38-cp38-win_amd64.whl
Collecting playsound>=1.2.2 (from wplay)
  Using cached https://files.pythonhosted.org/packages/f5/16/10d897b0a83fb4b05b03a63d7a2667ab75f857f67f7062fd447dd3f49bf7/playsound-1.2.2-py2.py3-none-any.whl
Collecting pyfiglet>=0.8.post1 (from wplay)
  Using cached https://files.pythonhosted.org/packages/33/07/fcfdd7a2872f5b348953de35acce1544dab0c1e8368dca54279b1cde5c15/pyfiglet-0.8.post1-py2.py3-none-any.whl
Collecting whaaaaat>=0.5.2 (from wplay)
  Using cached https://files.pythonhosted.org/packages/85/06/299520d293ec7a654f3b71453fee348011e6366f80cb6140181e438f6f9c/whaaaaat-0.5.2.tar.gz
Collecting requests>=2.22.0 (from wplay)
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting transitions>=0.7.2 (from wplay)
  Using cached https://files.pythonhosted.org/packages/38/62/f4e2453f11761861dd303d0b1df582a32271bdfe9a761633489d00cee414/transitions-0.8.0-py2.py3-none-any.whl
Collecting prompt-toolkit==1.0.14 (from wplay)
  Using cached https://files.pythonhosted.org/packages/ee/3d/b25d35a9f0d381dd1c02d8e04b37c353caaaff4bc32150328eeebe4931f5/prompt_toolkit-1.0.14-py3-none-any.whl
Collecting argparse>=1.4.0 (from wplay)
  Using cached https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl
Collecting beautifulsoup4>=4.8.1 (from wplay)
  Using cached https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl
Collecting flake8>=3.7.9 (from wplay)
  Using cached https://files.pythonhosted.org/packages/f8/1f/7ea40d1e4146ea55dbab41cda1376db092a75794914169aabd7e8d7a7def/flake8-3.7.9-py2.py3-none-any.whl
Collecting future>=0.16.0 (from python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting tornado>=5.1 (from python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/0c/04/48f7aca638106a57a94f9f3921fae27a9010076bccc9d31eef99c62ffaf5/tornado-6.0.4-cp38-cp38-win_amd64.whl
Collecting cryptography (from python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/27/da/8ee8775f0b6883b6c53e3f2d8a9a1e109661176446ec09f27c070dfc7baf/cryptography-2.8-cp38-cp38-win_amd64.whl
Collecting certifi (from python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting decorator>=4.4.0 (from python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting pyee (from pyppeteer>=0.0.25->wplay)
  Using cached https://files.pythonhosted.org/packages/d4/ce/a9a45667cdffbda2af63baa3ad1adca2feb80abf307d0dc91f9dfdfb3ec3/pyee-7.0.1-py2.py3-none-any.whl
Collecting websockets (from pyppeteer>=0.0.25->wplay)
  Using cached https://files.pythonhosted.org/packages/36/82/5797b2760cbbcfef28eb9060c6469c447f77e34c95e6ded7833655011fc7/websockets-8.1-cp38-cp38-win_amd64.whl
Collecting appdirs (from pyppeteer>=0.0.25->wplay)
  Using cached https://files.pythonhosted.org/packages/56/eb/810e700ed1349edde4cbdc1b2a21e28cdf115f9faf263f6bbf8447c1abf3/appdirs-1.4.3-py2.py3-none-any.whl
Collecting urllib3 (from pyppeteer>=0.0.25->wplay)
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Collecting tqdm (from pyppeteer>=0.0.25->wplay)
  Using cached https://files.pythonhosted.org/packages/47/55/fd9170ba08a1a64a18a7f8a18f088037316f2a41be04d2fe6ece5a653e8f/tqdm-4.43.0-py2.py3-none-any.whl
Collecting zope.interface (from datetime>=4.3->wplay)
  Using cached https://files.pythonhosted.org/packages/7a/d6/8edc1ace2ea8f006f13b3d19848aa9c0917e38bc4783dbd2c41d233bac28/zope.interface-5.0.1-cp38-cp38-win_amd64.whl
Collecting pytz (from datetime>=4.3->wplay)
  Using cached https://files.pythonhosted.org/packages/e7/f9/f0b53f88060247251bf481fa6ea62cd0d25bf1b11a87888e53ce5b7c8ad2/pytz-2019.3-py2.py3-none-any.whl
Collecting Pygments>=2.2.0 (from whaaaaat>=0.5.2->wplay)
  Using cached https://files.pythonhosted.org/packages/2d/68/106af3ae51daf807e9cdcba6a90e518954eb8b70341cee52995540a53ead/Pygments-2.6.1-py3-none-any.whl
Collecting regex>=2016.11.21 (from whaaaaat>=0.5.2->wplay)
  Using cached https://files.pythonhosted.org/packages/1a/9b/e203de9e65b0c6cb6040d82845c0943079892993b818657fe85dda3be89d/regex-2020.2.20-cp38-cp38-win_amd64.whl
Collecting idna<3,>=2.5 (from requests>=2.22.0->wplay)
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests>=2.22.0->wplay)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting six (from transitions>=0.7.2->wplay)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit==1.0.14->wplay)
  Using cached https://files.pythonhosted.org/packages/f6/d5/1ecdac957e3ea12c1b319fcdee8b6917ffaff8b4644d673c4d72d2f20b49/wcwidth-0.1.9-py2.py3-none-any.whl
Collecting soupsieve>=1.2 (from beautifulsoup4>=4.8.1->wplay)
  Using cached https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Collecting entrypoints<0.4.0,>=0.3.0 (from flake8>=3.7.9->wplay)
  Using cached https://files.pythonhosted.org/packages/ac/c6/44694103f8c221443ee6b0041f69e2740d89a25641e62fb4f2ee568f2f9c/entrypoints-0.3-py2.py3-none-any.whl
Collecting pyflakes<2.2.0,>=2.1.0 (from flake8>=3.7.9->wplay)
  Using cached https://files.pythonhosted.org/packages/84/f2/ed0ffb887f8138a8fe5a621b8c0bb9598bfb3989e029f6c6a85ee66628ee/pyflakes-2.1.1-py2.py3-none-any.whl
Collecting pycodestyle<2.6.0,>=2.5.0 (from flake8>=3.7.9->wplay)
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting mccabe<0.7.0,>=0.6.0 (from flake8>=3.7.9->wplay)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography->python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/b4/78/eefed9f51baa2b2c891915b4590a237ed6bc6d02beec177fc503bae8eb53/cffi-1.14.0-cp38-cp38-win_amd64.whl
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\site-packages (from zope.interface->datetime>=4.3->wplay) (41.2.0)
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography->python-telegram-bot>=11.1.0->wplay)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: future, tornado, pycparser, cffi, six, cryptography, certifi, decorator, python-telegram-bot, pyee, websockets, appdirs, urllib3, tqdm, pyppeteer, zope.interface, pytz, datetime, psutil, playsound, pyfiglet, wcwidth, prompt-toolkit, Pygments, regex, whaaaaat, idna, chardet, requests, transitions, argparse, soupsieve, beautifulsoup4, entrypoints, pyflakes, pycodestyle, mccabe, flake8, wplay
  Running setup.py install for future ... done
  WARNING: The script tqdm.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for pyppeteer ... done
  WARNING: The script pyfiglet.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for whaaaaat ... done
  WARNING: The script chardetect.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyflakes.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pycodestyle.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flake8.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wplay.exe is installed in 'C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Pygments-2.6.1 appdirs-1.4.3 argparse-1.4.0 beautifulsoup4-4.8.2 certifi-2019.11.28 cffi-1.14.0 chardet-3.0.4 cryptography-2.8 datetime-4.3 decorator-4.4.2 entrypoints-0.3 flake8-3.7.9 future-0.18.2 idna-2.9 mccabe-0.6.1 playsound-1.2.2 prompt-toolkit-1.0.14 psutil-5.7.0 pycodestyle-2.5.0 pycparser-2.20 pyee-7.0.1 pyfiglet-0.8.post1 pyflakes-2.1.1 pyppeteer-0.0.25 python-telegram-bot-12.4.2 pytz-2019.3 regex-2020.2.20 requests-2.23.0 six-1.14.0 soupsieve-2.0 tornado-6.0.4 tqdm-4.43.0 transitions-0.8.0 urllib3-1.25.8 wcwidth-0.1.9 websockets-8.1 whaaaaat-0.5.2 wplay-7.0.0 zope.interface-5.0.1
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

Then I upgraded pip by -->

`PS C:\Users\alexa> python -m pip install --upgrade pip                                                                                                                                                                                       Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
Installing collected packages: pip
Successfully installed pip-20.0.2`

Then tried something in wplay -->
`PS C:\Users\alexa> python -m wplay -wc "test"                                                                                                                                                                                                                 __
 _      ______  / /___ ___  __
| | /| / / __ \/ / __ `/ / / /
| |/ |/ / /_/ / / /_/ / /_/ /
|__/|__/ .___/_/\__,_/\__, /
      /_/            /____/

? ***Session Manager***:  Create a new session
? Write your first name or username to save:  alex
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 133194757/133194757 [00:14<00:00, 8994949.18it/s]
[W:pyppeteer.chromium_downloader]
chromium download done.
[W:pyppeteer.chromium_downloader] chromium extracted to: C:\Users\alexa\AppData\Local\pyppeteer\pyppeteer\local-chromium\575458
Process Killed!
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\__main__.py", line 150, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\__main__.py", line 143, in main
    await get_and_match_args(parser)
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\__main__.py", line 111, in get_and_match_args
    await wchat.chat(args.target)
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\wchat.py", line 16, in chat
    page, _ = await browser_config.configure_browser_and_load_whatsapp()
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\utils\browser_config.py", line 39, in configure_browser_and_load_whatsapp
    browser = await __config_browser(username, save_session)
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wplay\utils\browser_config.py", line 80, in __config_browser
    return await launch(
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyppeteer\launcher.py", line 311, in launch
    return await Launcher(options, **kwargs).launch()
  File "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyppeteer\launcher.py", line 167, in launch
    self.proc = subprocess.Popen(  # type: ignore
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.752.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 14001] Diese Anwendung konnte nicht gestartet werden, da die Side-by-Side-Konfiguration ungültig ist. Weitere Informationen finden Sie im Anwendungsereignisprotokoll. Weitere Details können auch mit dem Befehlszeilentool sxstrace.exe angezeigt werden
PS C:\Users\alexa> `

@rpotter12 I followed all of the instructions they where explained in your link.

I executed:
"sfc /scannow"

And after this, I removed all Microsoft Visual C++ Packages and installed them again.


I really wonder that I have the same Problem with 2 different PCs.

Why I can´t run chromium in the Path "C:\Users\alexa\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pyppeteer\pyppeteer\local-chromium\575458\chrome-win32" but when I copy this to my desktop I can run chromium without problems?

Thanks for you help

**Comment by rpotter12** [comment]
I dunno know. I don't use windows so I can't answer this :)

**Comment by dogexan** [comment]
What operating system do you use? Maybe I will try this in VirtualBox

**Comment by xandao6** [comment]
I use windows, but I don't know what's going on.

**Comment by priyansh19** [comment]
Hey @dogexan,
I am not sure but can you try to make a Linux virtual machine and install wplay in it 
It will a lot simpler if you know how to use AWS free virtual machines. 
Spin Up a Linux Virtual Machine in AWS or any cloud .. connect to it using SSH and then try installing wplay in it .. It will work most probably

**Comment by priyansh19** [comment]
It does worked with 4 participants .. And don't forget to stop Instead of terminating your instance after using it

**Comment by dogexan** [comment]
Ok, I tried it in Ubuntu 19.10 and it works fine. I don´t know where the Problem is in my Windows installations. So if no one else has the same problem as me, then I would say we close this issue. It seems to be a problem only for me.

Many thanks for your support
