### ISSUE TITLE
docker image for whatsapp-play

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#21]

**Comment by mridubhatnagar** [comment]
I am gssoc participant. I am interested in working on this issue.
I don't know docker. Btw curious to learn and explore.

**Comment by mridubhatnagar** [comment]
@rpotter12 @xandao6 any update on this?

**Comment by xandao6** [comment]
@mridubhatnagar We don't know docker, we just know that is good. You will need to learn it, the main purpose is to create an easy and universal installation environment.

**Comment by mridubhatnagar** [comment]
@rpotter12 @xandao6 can this task be assigned to me? I am interested in tinkering around with docker.

**Comment by xandao6** [comment]
@mridubhatnagar we are deciding how issues will be assigned, but it is important to know your interest, take a look at slack.

**Comment by mridubhatnagar** [comment]
Pinged on slack

**Comment by xandao6** [comment]
@mridubhatnagar done, you have 4 days.

**Comment by mridubhatnagar** [comment]
Thanks. Working on it.

**Comment by mridubhatnagar** [comment]
Hey, before I start with the implementation.

I just wanted to know what was the use case which made you think that docker would be a nice solution to solve the problem?

I am kind of reading docker stuff. I trying to understand where docker fits in.

**Comment by xandao6** [comment]
@mridubhatnagar deadline extended +4d

**Comment by manaswitatyagi** [comment]
Please let me know, if I can work on this issue later on. 
Thanks!

**Comment by xandao6** [comment]
@manaswitatyagi assigned

**Comment by xandao6** [comment]
@mridubhatnagar  re-assigned

**Comment by mridubhatnagar** [comment]
@xandao6 just wanted to confirm that are you folks using the existing docker file in the repo?

**Comment by xandao6** [comment]
@mridubhatnagar nobody is using it, it's an old file.

**Comment by rpotter12** [comment]
@mridubhatnagar That was the initial file but was implemented fully.

**Comment by rpotter12** [comment]
Our script uses pyppeteer package which opens a chrome browser when the scripts starts. So we have to make dockerfile like this that it opens a browser for docker image.

**Comment by priyansh19** [comment]
@mridubhatnagar any update on this issue ?

**Comment by SinghHimadri** [comment]
I would like to work on this issue please assign it to me.

**Comment by xandao6** [comment]
@SinghHimadri Assigned
