### ISSUE TITLE
Change target person during chat in CLI(idea)

### ISSUE THREAD

**Issue by zulkernine** [rpotter12/whatsapp-play#217]
Once chat started (wchat) with a person, we've to restart the application to change target name.
Adding an option to change the target person during 'wchat' will make the application more flexible.

**Comment by zulkernine** [comment]
Please assign me this issue.

**Comment by zulkernine** [comment]
@xandao6 please assign me this issue.

**Comment by zulkernine** [comment]
I made a commit to solve this issue. please view the PR #222 . Here's a screenshot demonstrating the feature.
![issue217_demonstration1](https://user-images.githubusercontent.com/53091788/76934099-80d61e80-6914-11ea-9db9-b445803a963b.png)

**Comment by xandao6** [comment]
nice

**Comment by priyansh19** [comment]
:+1:

**Comment by zulkernine** [comment]
Should I close this issue now?
