### ISSUE TITLE
Create a new Pull_Request_Template

### ISSUE THREAD

**Issue by priyansh19** [rpotter12/whatsapp-play#233]
This will help the users while creating the PR's as they will discuss the changes and the files changed and all the features this PR will be adding.

- Sample Pull_Request_Template: https://github.com/apache/spark/blob/master/.github/PULL_REQUEST_TEMPLATE

- To take help from Docs: https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by Aman-Codes** [comment]
@priyansh19 I would like to work on this issue please assign me this issue. I have already created a template so do let me know if you need any changes in it.
## Screenshots
### Pull Request
![pull request](https://user-images.githubusercontent.com/54680709/77220497-9c386800-6b66-11ea-9d0a-72820d72a239.PNG)
