### ISSUE TITLE
Showing Error on tracking the person whose read-receipt is off.

### ISSUE THREAD

**Issue by csharp489** [rpotter12/whatsapp-play#240]
When I try to track a person whose read-receipt is off on whatsapp, then it shows an error that **No contact named by "Any_Name"!** and also give an **UnboundLocalError**.
I think this is very wrong representation. We should simply give a statement that tracking data is unable to find.(use some conditional statement).
![tracking](https://user-images.githubusercontent.com/42842260/77246168-91ef9a00-6c4a-11ea-8ee8-89b7db120651.PNG)

**Comment by xandao6** [comment]
We have a new version that has not yet been published in pypi. Try it.
Open a terminal and follow the commands: 
`git clone https://github.com/rpotter12/whatsapp-play.git`
`cd whatsapp-play`
`python3 -m wplay -wt "sapna strps"`

**Comment by rpotter12** [comment]
@csharp489 Use exact name of the person. The script is showing `No contact named by "sapna strps"`
