### ISSUE TITLE
Even the Module is present BUT still it is giving ModuleNotFoundError 

### ISSUE THREAD

**Issue by csharp489** [rpotter12/whatsapp-play#241]
When I try to run Message Bombing command it gives as error that **ModuleNotFoundError: No module named 'pyfiglet'** Even I have already installed the pyfiglet module.
![mesgBomb](https://user-images.githubusercontent.com/42842260/77246295-d0398900-6c4b-11ea-9507-57ddeb2756fb.PNG)

**Comment by xandao6** [comment]
Hello, install pyfiglet and any other module with the following command:
`python3 -m pip install pyfiglet`

**Comment by xandao6** [comment]
When you install with by pip you are probably installing the module for python 2.

**Comment by rpotter12** [comment]
Use command `pip list` to list all the packages installed by you. Check if pyfiglet is there or not.

**Comment by csharp489** [comment]
Now, it is working . Thanks for the instant reply.
