### ISSUE TITLE
Add methods/options to send media/file through wchat ( Idea )

### ISSUE THREAD

**Issue by zulkernine** [rpotter12/whatsapp-play#244]
Currently we can send text messages only. But we often need to send media files ( pictures or videos) or documents ( pdf, .TXT, .docx etc) . Adding such features will increase the functionality.

**Comment by xandao6** [comment]
@zulkernine wanna be assigned?

**Comment by zulkernine** [comment]
Yes .

**Comment by zulkernine** [comment]
Should I make different options for Image/video sharing and docx/pdf sharing or a single options to share any file ??
