### ISSUE TITLE
Duplication of Commands in README

### ISSUE THREAD

**Issue by iharshit009** [rpotter12/whatsapp-play#247]
![Screenshot from 2020-03-24 01-35-28](https://user-images.githubusercontent.com/44135316/77358421-d6c12100-6d6f-11ea-85b3-b5f4d7103afc.png)
![Screenshot from 2020-03-24 01-35-47](https://user-images.githubusercontent.com/44135316/77358425-d7f24e00-6d6f-11ea-8d03-7e991df25271.png)

**Comment by xandao6** [comment]
where is the duplication?
