### ISSUE TITLE
Add CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by Aman-Codes** [rpotter12/whatsapp-play#253]
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@rpotter12 As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project.

**Additional context**
### Screenshots

![code of conduct1](https://user-images.githubusercontent.com/54680709/77505634-beddc000-6e89-11ea-9dd5-f1e13ef6c6c9.PNG)
![code of conduct2](https://user-images.githubusercontent.com/54680709/77505638-c0a78380-6e89-11ea-8aa4-efcb21133da7.PNG)

**Comment by Aman-Codes** [comment]
@rpotter12  Sir can you please share your email id which I can add in this file where participants can report any unacceptable behavior .

**Comment by rpotter12** [comment]
Email - rohitpotter12@gmail.com

**Comment by shwhite17** [comment]
will you please add this assign to me?
