### ISSUE TITLE
Broadcast Idea

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#273]
Load a file with phone numbers and send a message to all of them! The difference between this and the Whatsapp broadcast in smartphone is that we can send message even if we don't have that contact!

**Comment by zulkernine** [comment]
I would like to work on this. I just got a reference that how to send message through api.whatsapp.com, here's a link of it : https://www.androidpit.com/send-whatsapp-message-without-adding-contact-to-address-book . Can i implement it here? Or please suggest some better ways.

**Comment by xandao6** [comment]
@zulkernine I'm refactoring the project and I already included this feature to send message to unknown number. I will release it soon. So wait for my release to start working on this issue.

**Comment by zulkernine** [comment]
Ok. I'm waiting ☺️

**Comment by zulkernine** [comment]
What is the type of the file ?
In which format will it contains those numbers??

**Comment by xandao6** [comment]
a simple txt, 1 number per line:

9194848948
4848946548
4684848648

**Comment by zulkernine** [comment]
Alright

**Comment by zulkernine** [comment]
Should I use that api to send message to unsaved number?
In that case , whatsapp web will be opened in the new tab again, thus it would take a very long time. 
So what should I do??

**Comment by xandao6** [comment]
use this method: search_and_select_target. It will detect the number and load the page, without opening a new one

**Comment by xandao6** [comment]
so you can put it in a for loop:
```
for number in numbers:
    search_and_select_target(page, number)
    send message
```

**Comment by zulkernine** [comment]
I got the idea :)
I'm starting to implement it . 
I'll make the commit soon.

**Comment by zulkernine** [comment]
Searching the target(through number) more than once gives this pop up. How to disable this pop up ?
[1904.05104.pdf](https://github.com/rpotter12/whatsapp-play/files/4452584/1904.05104.pdf)
![WhatsApp Image 2020-04-09 at 1 34 56 AM](https://user-images.githubusercontent.com/53091788/78828719-c44b1680-7a02-11ea-8170-4aa496ef24ef.jpeg)
![WhatsApp Image 2020-04-09 at 1 36 40 AM](https://user-images.githubusercontent.com/53091788/78828728-c6ad7080-7a02-11ea-84ef-1a8791650b1a.jpeg)

**Comment by zulkernine** [comment]
My code is ready for commit except this issue(Mentioned upper).

**Comment by zulkernine** [comment]
> a simple txt, 1 number per line:
> 
> 9194848948
> 4848946548
> 4684848648



Should I assume all the numbers are correct and has a whatsapp account?
Number will contain country code or not?

I implemented it in such a way that if country code is provided then alright otherwise indian country code is used.

**Comment by xandao6** [comment]
https://stackoverflow.com/questions/46669788/how-to-handle-popups-in-puppeteer

**Comment by xandao6** [comment]
skip the number if error and log a message.

**Comment by zulkernine** [comment]
> skip the number if error and log a message.

Existing target_search method exit the program if wrong number is used.
So I think , I'm to make a custom function for this case.

**Comment by zulkernine** [comment]
> skip the number if error and log a message.

Following error is skipped in the __try_load_contact_by_number() in target search. Consequently, Though the number is invalid, this function is returning true leading to exit call in __get_focused_target_title(). :(

![Screenshot from 2020-04-09 11-21-35](https://user-images.githubusercontent.com/53091788/78862424-fbe2ae80-7a54-11ea-9bcc-387ad4575ba9.png)

**Comment by xandao6** [comment]
You will need to watch this message box, using waitForSelector

**Comment by xandao6** [comment]
Think that all numbers are valid, I will fix this in the weekend.

**Comment by zulkernine** [comment]
Ok

**Comment by zulkernine** [comment]
A PR is created regarding this issue .
Please review.

**Comment by zulkernine** [comment]
What happened? What about that PR?
