### ISSUE TITLE
Adding Calendar view in CLI to set important dates and events

### ISSUE THREAD

**Issue by priyansh19** [rpotter12/whatsapp-play#282]
We will add a calendar in our wplay cli option to schedule a reminder of events and important dates

**Comment by amandhamija98** [comment]
Will this reminder be one in google calendar?

**Comment by rpotter12** [comment]
By setting up any remainder will not work if the software is stopped. For this type of issue, our software should keep working all the time.

**Comment by amandhamija98** [comment]
I see, currently without running a cron job it wont be possible to send an email on the day the reminder is supposed to be shown. We can use the google calendar API, but we would need to register the project with google cloud platform

**Comment by priyansh19** [comment]
For now .. just for basic functionality Add a callender view in CLI in which reminders can be added , deleted and viewed

**Comment by amandhamija98** [comment]
ok, I will look into this

**Comment by rpotter12** [comment]
@amandhamija98 wait for now. This is not needed yet. Let everybody should clear the whole idea.

**Comment by amandhamija98** [comment]
Sure
