### ISSUE TITLE
Bug in Target_search regarding invalid number

### ISSUE THREAD

**Issue by zulkernine** [rpotter12/whatsapp-play#283]
If invalid number is passed as argument to search_and_select_target in target_search.py or if no account exist  of that number following error is skipped in the __try_load_contact_by_number() . Consequently, though the number is invalid, this function is returning true leading to exit call in __get_focused_target_title().

![IMG_20200409_115025](https://user-images.githubusercontent.com/53091788/78865470-4c5d0a80-7a5b-11ea-966e-c89867a8a15a.jpg)

My OS : Kali 2020.2
Browser: Chromium 80.0.3987.132

**Comment by zulkernine** [comment]
Help Wanted.

**Comment by xandao6** [comment]
I can fix it on the weekend

**Comment by zulkernine** [comment]
Ok.

**Comment by amandhamija98** [comment]
Can i please be assigned this

**Comment by rpotter12** [comment]
@amandhamija98 Start working on this. :)

**Comment by amandhamija98** [comment]
sure
