### ISSUE TITLE
Send Images from CLI (Idea) **efficiently**

### ISSUE THREAD

**Issue by priyansh19** [rpotter12/whatsapp-play#289]
Images should be send through `-wc` option.

**Comment by priyansh19** [comment]
@rpotter12 @xandao6 is it a valid issue ?

**Comment by xandao6** [comment]
We already can send images through -wc, but we need a better way to do this.

**Comment by zulkernine** [comment]
🤔🤔 
How it would be more efficient for user to sent file through cli?
Should the option for writing a caption be added??

**Comment by priyansh19** [comment]
We can add a separate option to send an image and audio alone

**Comment by rpotter12** [comment]
Chatting should be from one option only. All types of chatting should be done from `-wc` command only.

**Comment by SinghHimadri** [comment]
Can you explain this issue in detail.
