### ISSUE TITLE
Send Audio From CLI (IDEA)

### ISSUE THREAD

**Issue by priyansh19** [rpotter12/whatsapp-play#290]
audio message should be send through `-wc` option.

**Comment by priyansh19** [comment]
@rpotter12 @xandao6 is it a valid issue ?

**Comment by priyansh19** [comment]
@xandao6 Can we send audio from CLI ?

**Comment by xandao6** [comment]
yees

**Comment by priyansh19** [comment]
@xandao6 add labels to this issue

**Comment by zulkernine** [comment]
Audio can be sent through -wc options . What other methods should be implemented 🤔

**Comment by priyansh19** [comment]
Yes it is a valid option .. we can add

**Comment by SinghHimadri** [comment]
I would like to work on this issue.
