### ISSUE TITLE
A script for sending emails through cli.

### ISSUE THREAD

**Issue by amandhamija98** [rpotter12/whatsapp-play#292]
This idea would involve writing a script for sending emails to a target email address. The inputs would be the sender's email, the receiver's email, the subject and the message.

**Comment by amandhamija98** [comment]
May I work on this

**Comment by rpotter12** [comment]
@amandhamija98 How it is related to Whatsapp?? Please explain.

**Comment by amandhamija98** [comment]
To be honest it isn't, I just thought it could be a useful feature , kind of like the news script

**Comment by priyansh19** [comment]
We can do one thing that the message will be forwarded to directly a mail .. if that's a possibility

**Comment by amandhamija98** [comment]
Sure that is possible, we'd need the sender's and reciever's email before the chat begins

**Comment by xandao6** [comment]
It is possible, but it is a bit annoying for the user since he will have to configure the SMTP server
