### ISSUE TITLE
location finder (Idea)

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#31]
script to find the location of person just by the name argument of the person

**Comment by rpotter12** [comment]
https://www.youtube.com/watch?v=WW6myutKBYk&feature=youtu.be 
We can use this method to find the location initially

**Comment by shvamabps** [comment]
can we use an API for this purpose where we can return location in JSON format and fetch from there

**Comment by xandao6** [comment]
which API?

**Comment by shvamabps** [comment]
gmaps api

**Comment by shvamabps** [comment]
Please assign me this issue
I can work on it

**Comment by xandao6** [comment]
@shvamabps done, you have 4 days.

**Comment by shvamabps** [comment]
Can you extend the deadline for this issue??

**Comment by xandao6** [comment]
Sure, more 4 days, you can ask more ultil there is someone in queue

**Comment by manaswitatyagi** [comment]
@xandao6 , I am really interested in working on  this issue. It seems like the deadline is over so do you mind assigning me to it?

**Comment by xandao6** [comment]
@manaswitatyagi assigned

**Comment by shvamabps** [comment]
@manaswitatyagi  where have you reached to this issue 
as  I guess the time is also extended for this

**Comment by xandao6** [comment]
@shvamabps re-assigned

**Comment by SinghHimadri** [comment]
I would like to work on this issue please assign it to me.

**Comment by xandao6** [comment]
@SinghHimadri
