### ISSUE TITLE
Chromium not working.

### ISSUE THREAD

**Issue by ahmed-gelemli** [rpotter12/whatsapp-play#310]
What I did wrong? Chromium opens, but nothing happens.

**https://streamable.com/ei0p19**

**Comment by xandao6** [comment]
Windows 10 64bits?

**Comment by rpotter12** [comment]
Kindly uninstall the software and install it again. I think the problem is installation.

**Comment by ahmed-gelemli** [comment]
> Windows 10 64bits?

Yep.

**Comment by ahmed-gelemli** [comment]
> Kindly uninstall the software and install it again. I think the problem is installation.

Ok, I uninstalled wplay using 'python -m pip uninstall wplay', and reinstalled chromium.

**Comment by ahmed-gelemli** [comment]
> > Kindly uninstall the software and install it again. I think the problem is installation.
> 
> Ok, I uninstalled wplay using 'python -m pip uninstall wplay', and reinstalled chromium.

But the same problem occurs.

**Comment by rpotter12** [comment]
Share your error screenshot here. :)

**Comment by ahmed-gelemli** [comment]
Umm, I don't know why, but now it's working so well! Thanks! :)
