### ISSUE TITLE
Not reveiving messages in group chat

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#334]
I was trying to test the chatbot. I found a bug that we are not receiving messages in group chat. 
I ran the script by - `wplay -wc`, then select the group but I didn't receive the last message in it.

**Comment by m-code12** [comment]
@rpotter12 I would like to work on this . Please assign me .

**Comment by rpotter12** [comment]
@m-code12 start working on it :)

**Comment by m-code12** [comment]
@rpotter I am receiving and able  to send messages successfully while I run wplay  -wc "Group name"

![image](https://user-images.githubusercontent.com/53649201/82112367-d8a0d280-9769-11ea-8b3f-8171e1a39397.png)

**Comment by priyansh19** [comment]
@m-code12 What @rpotter12 mean to say is .. we aren't recieving messages back in terminal 

You need to work on that

**Comment by SinghHimadri** [comment]
Can I work on this issue now?

**Comment by m-code12** [comment]
@rpotter12 You can assign the issue to @SinghHimadri .
