### ISSUE TITLE
Profile Picture Download for a single user

### ISSUE THREAD

**Issue by soumyashaw** [rpotter12/whatsapp-play#336]
The User should be able to check & save the changed profile picture of a target in target's personal folder if he/she uploads a new profile picture in this feature.

**Comment by SinghHimadri** [comment]
I would like to work on this issue.

**Comment by soumyashaw** [comment]
I'm already working on it bro!

**Comment by soumyashaw** [comment]
> I would like to work on this issue.

Already working on it bro.
