### ISSUE TITLE
Target Info fails to fetch data

### ISSUE THREAD

**Issue by soumyashaw** [rpotter12/whatsapp-play#348]
The feature of Target info fails to operate and fetch the information requested.

![image](https://user-images.githubusercontent.com/37841510/82367693-d40e3f80-9a31-11ea-8036-f61159ce8ffb.png)

**Comment by rpotter12** [comment]
@soumyashaw May be you messed up with your scripts by applying minizing browser feature. :)

**Comment by soumyashaw** [comment]
Working Now
