### ISSUE TITLE
Add colorama to requirements.txt

### ISSUE THREAD

**Issue by HeroicHitesh** [rpotter12/whatsapp-play#354]
Reference PR #353 
`colorama` needs to be added to `requirements.txt`
@rpotter12 @priyansh19 I am interested to work on this issue.

**Comment by rpotter12** [comment]
@HeroicHitesh I would like to suggest add all libraries in requirements.txt which are used in software but not written in requirements.txt file.

**Comment by HeroicHitesh** [comment]
@rpotter12 have a look at PR #356 it should resolve this issue.
