### ISSUE TITLE
Whatsapp not opening in full-screen on Chromium

### ISSUE THREAD

**Issue by HeroicHitesh** [rpotter12/whatsapp-play#355]
@rpotter12 @xandao6 @priyansh19 
While running `whatsapp-play` if due to some command WhatsApp opens in chromium it is never opening in full screen. 
Is it some kind of bug or intended feature? 
If it's a bug I would like to work on it so, please direct me to the associated file in codebase so, I can give it a try.

SS of issue
<img width="1194" alt="Screenshot 2020-05-22 at 10 22 16 AM" src="https://user-images.githubusercontent.com/37622734/82640673-a0493a80-9c28-11ea-8794-cddef9def06a.png">

Expected view
<img width="1440" alt="Screenshot 2020-05-22 at 12 37 53 PM" src="https://user-images.githubusercontent.com/37622734/82640971-2f565280-9c29-11ea-8225-34df8e680685.png">

**Comment by priyansh19** [comment]
It's not a bug .. In the main code file the dimensions are intentionally added .. If you want your window to be a full screen then you can change the dimensions on your end 🙂
