### ISSUE TITLE
Update read.me file

### ISSUE THREAD

**Issue by himanshujaidka** [rpotter12/whatsapp-play#372]
What are the tools required for installing this in the system? Update the Readme file.

**Comment by rpotter12** [comment]
@himanshujaidka Please read the Installation portion in readme.md file. Everything is clearly written in that :)

**Comment by himanshujaidka** [comment]
![error](https://user-images.githubusercontent.com/58654018/83855562-e2e53980-a735-11ea-865a-4024201230c8.png)
when I installed, this error came up. pls, help me as I am a beginner.

**Comment by rpotter12** [comment]
Not able to view your error image. Create a new issue for your error :)
