### ISSUE TITLE
Contact not switching at first try

### ISSUE THREAD

**Issue by Pushpit07** [rpotter12/whatsapp-play#381]
I was sending a message to person 'A' and then switched the contact to person 'B' to send a message to him. I did this by executing ```...```. But then I thought that I don't want to send a message to 'B', rather I would like to send a message to 'C'. I again executed ```...``` to switch to person 'C' but "..." was sent as a message to person 'B'. This issue happens only when we execute ```...``` the first time after switching to a contact. I think that this should be fixed

**Comment by rpotter12** [comment]
@Pushpit07 Thank you :)
If you like to work on this issue please proceed.

**Comment by Pushpit07** [comment]
> @Pushpit07 Thank you :)
> If you like to work on this issue please proceed.

Yes, sure. Working on it
