### ISSUE TITLE
i can't install wplay¡¡¡

### ISSUE THREAD

**Issue by acripa** [rpotter12/whatsapp-play#384]

**Comment by acripa** [comment]
no puedo instalar wplay me dice que visual studio no esta instalado, pero si lo esta.

**Comment by rpotter12** [comment]
@acripa English please :)

**Comment by acripa** [comment]
Hello, I'm sorry,
the problem is that i can't install wplay, there's no way, it gives me an error and says that i don't have visual studio installed, but i do, i have visual studio 2019 communitty.
What can I do?

**Comment by rpotter12** [comment]
@acripa 
Is this issue is still there??
If yes, can you paste the screenshot of the error you are getting
