### ISSUE TITLE
Detection of sentiments

### ISSUE THREAD

**Issue by sudipg4112001** [rpotter12/whatsapp-play#392]
I would like to add a project for sentiment analysis of users for the text of WhatsApp. I would like to do this using the dataset: https://www.kaggle.com/sankha1998/emotion
I am a participant of GSSOC'21

**Comment by rpotter12** [comment]
Hi @sudipg4112001, I don't think it will be better for this project. It will be good if you introduce a new feature in this software which we can't do with our Whatsapp mobile app. :)
