### ISSUE TITLE
Emojify text Emojis

### ISSUE THREAD

**Issue by bitaashna** [rpotter12/whatsapp-play#396]
A method to emojify all the text emoji's present in the message.
I would like to contribute to it as a part of GSSOC'21.
Can you please assign it to me,

**Comment by rpotter12** [comment]
Hi @bitaashna, I'm not clear with your idea. Can you share some example here?

**Comment by bitaashna** [comment]
Hey @rpotter12 !
as we know we cannot write emojis in the terminal so we may use text instead of that emojis and when we message someone than  that text will be converted to emoji

**Comment by bitaashna** [comment]
Ok. I'll try it and let you know.

**Comment by rpotter12** [comment]
This issue is solved by #409.
