### ISSUE TITLE
script for telegram bot

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#4]
currently, the script shows the online status in the terminal only. The idea of the project is to send the online status on the telegram bot. 
so we need to create a script to send the online status on telegram bot.

**Comment by cyberahm4d** [comment]
thanks for this, i would suggest saving the outcome in txt file for now till the telegram part is done.

**Comment by rpotter12** [comment]
@cyberahm4d thanks for the suggestion. For now we can do this too. :)

**Comment by rpotter12** [comment]
@cyberahm4d Please go ahead in implementation of your suggestion. :)
