### ISSUE TITLE
Automatic Message Send to WhatsApp browser 

### ISSUE THREAD

**Issue by anubhav201241** [rpotter12/whatsapp-play#408]
Is this feature I can create an Automation of  WhatsApp Chats 

In this we Type message and decide at what time to send the message and to whom send the message 

This can make our work more easier and reduce our time too 

Simple Automation of WhatsApp chat (Sending the message to whomever we want)

:))

**Comment by A-kriti** [comment]
Hello Anubhav Sir, I would like to contribute to this issue as a GSSOC'21 participant. So could you please assign me this?

**Comment by anubhav201241** [comment]
> Hello Anubhav Sir, I would like to contribute to this issue as a GSSOC'21 participant. So could you please assign me this?

I'm Not Sir I'm also a Participant and want to contribute this to the Project :)

**Comment by rpotter12** [comment]
Hi @anubhav201241, this feature is already present in this software. Please schedule-message feature.
