### ISSUE TITLE
Update Contributing.md

### ISSUE THREAD

**Issue by khareyash05** [rpotter12/whatsapp-play#411]
Hi! I would like to add few things in contributing.md apart from the one mentioned
1. Squash commits of an issue under a single commit
2. Update your forked and local repo as and when changes are made in the upstream

**Comment by rpotter12** [comment]
Hi @khareyash05, There is no need of first point. I can squash and commit while merging a PR if it is needed. You can add second point.

**Comment by soumik2012** [comment]
Can I also contribute to this?

**Comment by anushree71199** [comment]
If this is still open I would like to contribute to this issue under GSSoc'21. Can you assign it to me?

**Comment by khareyash05** [comment]
Sorry @soumik2012 @anushree71199  I have already finished it and just waiting for merging

**Comment by khareyash05** [comment]
Thank You!
@rpotter12 Could you please add a level label to the same as under the GSSOC guidelines? As easy labels aren't being evaluated in GSSOC
