### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by smarteutech** [rpotter12/whatsapp-play#44]
Hi!
Thanks for Your hard work. I am new in python and I want test this repo for my personal use of tracking. I have installed pip3 in centos7 and also installed repo as instruction given in readme file. Sorry but I am not advanced user and so I don't know how I can connect number with machine etc so I am not able to run it. 
I have followed below step

1) Installed PIP3
2) Installed Repo using command pip3 install wplay
3) I dont know what next I should do and so I have tried command like
wplay -wt "raj" and its giving me error like below

```
 wplay -wt "raj"
Traceback (most recent call last):
  File "/usr/bin/wplay", line 7, in <module>
    from wplay.wplay import main
  File "/usr/lib/python3.4/site-packages/wplay/wplay.py", line 2, in <module>
    from wplay import onlinetracker
  File "/usr/lib/python3.4/site-packages/wplay/onlinetracker.py", line 7, in <module>
    from playsound import playsound
ImportError: No module named 'playsound'
```

Please help me for same. Thanks a lot :)

**Comment by rpotter12** [comment]
according to the error playsound module is not installed in your system. 
Use command `pip3 install playsound` to install the playsound module.

**Comment by rpotter12** [comment]
@smarteutech as playsound sound module is not written in setup.py, you can edit the setup.py file by adding `"playsound >=1.2.2"` in `install_requires` and open a pull request for it.

**Comment by smarteutech** [comment]
@rpotter12 Thanks for quick reply. I have still question about how to connect whatsapp with this. Thanks a lot.

**Comment by smarteutech** [comment]
After Install PlaySound, its giving me another error called `ImportError: cannot import name 'BeatifulSoup'
`
Thanks

**Comment by rpotter12** [comment]
@smarteutech To install beautifulsoup use command `pip3 install beautifulsoup4` and please don't use `wplay -ws "<persons_name>"` the savechat script is not completed yet. Please try another option wt etc :)

**Comment by rpotter12** [comment]
> @rpotter12 Thanks for quick reply. I have still question about how to connect whatsapp with this. Thanks a lot.

@smarteutech When the script will be executed the script will automatically open whatsapp web in chrome browser. Then you have to scan the scancode with your whatsapp account.
