### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by nileshpatra** [rpotter12/whatsapp-play#48]
Currently, wplay supports only Chrome browser. Let's add a support for firefox too.  The code would ask the user to choose the browser they would like to use and extension would be chosen accordingly.

**Comment by rpotter12** [comment]
@nileshpatra I was thinking that whether from asking from the user about the browser the script should automatically detect the browser.

**Comment by rpotter12** [comment]
As #72 is introduced. This issue can be closed.
