### ISSUE TITLE
Error: Command 'wplay' not found, after installing wplay by pip

### ISSUE THREAD

**Issue by moka1309** [rpotter12/whatsapp-play#60]
Hi,
I did "pip install wplay" after that I ran 
`wplay -wt "target_name_of_your_whatsapp_contact"`
But I got error as below
`Command 'wplay' not found, did you mean:

  command 'splay' from deb splay
  command 'qplay' from deb hxtools
  command 'bplay' from deb bplay
  command 'cplay' from deb cplay
  command 'aplay' from deb alsa-utils
  command 'play' from deb sox
  command 'rplay' from deb rplay-client

Try: sudo apt install <deb name>
`
Will anyone please give me a proper way to run this project successfully.

**Comment by rpotter12** [comment]
which OS are you using?

**Comment by moka1309** [comment]
I am using Ubuntu 18.04.

**Comment by rpotter12** [comment]
Reference Link: https://github.com/ritiek/spotify-downloader/issues/451#issuecomment-449552442

you most likely do not have the directory where python bin files get installed to in your $PATH environment variable.

Find where the python package got installed:

$ find ~/.local/ /usr/ -name wplay  
This should give you an output path ending with bin/wplay, so the full path should be something like [...]/bin/wplay.

We need to append this directory to the $PATH variable.

$ echo "export PATH='[...]/bin:$PATH'" >> ~/.bashrc
This should be it; try opening a new terminal and $ wplay --help.

**Comment by moka1309** [comment]
Thanks now its working good. But I find few bugs while working with wplay

1. RequestsDependencyWarning: urllib3 (1.25.6) or chardet (3.0.4) doesn't match a supported version!
`pip3 install urllib3==1.24.3 --user`
2. ModuleNotFoundError: No module named 'playsound'
`pip install playsound --user`
3. ImportError: cannot import name 'BeatifulSoup'
```
sudo nano [...]/.local/lib/python3.6/site-packages/wplay/savechat.py
change BeatifulSoup to BeautifulSoup
```

**Comment by rpotter12** [comment]
@moka1309 These all will be removed with the next version of the software. 

We need to test the whole software manually.

You can start working on this software by doing the whole manual testing
- `git clone https://github.com/rpotter12/whatsapp-play`
- `wplay --help` (to find all the options)

and execute all the features one by one and open issues if you find something not working. :)
