### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#62]
Hey @rpotter12 , why when I clone your repository I can't run the wplay? Only works when I do pip3 install wplay. I wanna edit and make new scripts.

**Comment by rpotter12** [comment]
Hi @xandao6 
You can run your own changed script by-

1. `git clone https://github.com/rpotter12/whatsapp-play`
2. `cd whatsapp-play`
3. `pip3 install .`

`pip3 install .` will install your changes in the wplay.

**Comment by xandao6** [comment]
Thank you, I will try.

**Comment by xandao6** [comment]
> Hi @xandao6
> You can run your own changed script by-
> 
>     1. `git clone https://github.com/rpotter12/whatsapp-play`
> 
>     2. `cd whatsapp-play`
> 
>     3. `pip3 install .`
> 
> 
> `pip3 install .` will install your changes in the wplay.

It works using global python, but didn't work inside virtual environment. 
What I have done with venv:
1. `python3 venv wplayVenv`
2. `source wplayVenv/bin/activate`
3. `pip install .`

**Comment by ritiek** [comment]
@xandao6 I'm not sure whether that results in an error or just plainly doesn't work for you?

I could confirm that this setup works fine for me:
```console
$ cd whatsapp-play
$ virtualenv wplay-env
$ source wplay-env/bin/activate
$ pip3 install -e .
```

If that went alright for you as well, `wplay` python executable should point to our newly created virtual env like so:
```console
$ which wplay
<...>/whatsapp-play/wplay-env/bin/wplay
```

Now you could modify the source code and then re-run the `wplay` command everytime you wish to execute your changes.

**Comment by xandao6** [comment]
I restarted my computer and now my method also works.
Thank you!
