### ISSUE TITLE
improve code quality

### ISSUE THREAD

**Issue by rpotter12** [rpotter12/whatsapp-play#66]
https://app.codacy.com/manual/rpotter12/whatsapp-play/dashboard?bid=13271659

According to this code quality is C. It should be improve.

How to improve code quality:
1. open https://app.codacy.com/manual/rpotter12/whatsapp-play/files?bid=13271659
2. solve errors written in each files.

**Comment by xandao6** [comment]
I'm working in a branch to refactor it!
