### ISSUE TITLE
Pyppeteer (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#72]
Migrate from Selenium to Pyppeteer to deal with asynchronous tasks.

**Comment by xandao6** [comment]
Drawbacks: Pyppeteer only works in Chrome.

**Comment by rpotter12** [comment]
@xandao6 It can be a good idea and currently we are using only Chrome web-browser. So we can apply this.

Please go ahead with your implementation :)

**Comment by xandao6** [comment]
I am about to finish the pyppeteer implementation. When I walked deep into this library it seemed a bit abandoned, what do you think about using both libraries (selenium and pyppeteer)? and over time we decide if we exclude any of these libraries.

So far so good with pyppeter, I'm bringing a lot of news!

**Comment by xandao6** [comment]
Do you want to create an alpha version to use pyppeteer? or leave it on an experimental branch?
If you want to create a new branch because I don't have that power.

**Comment by rpotter12** [comment]
@xandao6, for now, we create an experimental branch and test pyppeteer from that branch. When it performs same function as master branch code do then we will shift code to master branch.

**Comment by rpotter12** [comment]
@xandao6 I have created experimental branch. :)

**Comment by xandao6** [comment]
All done!

**Comment by xandao6** [comment]
Pyppeteer implemented in experimental branch!
https://github.com/rpotter12/whatsapp-play/pull/95
