### ISSUE TITLE
Save cookies (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#75]
Save cookies to make session reusable.
I think that isn't hard with Pyppetter.

**Comment by rpotter12** [comment]
@xandao6 yes we can do that. Let us first switch to pyppeteer.:)

**Comment by xandao6** [comment]
Actually, I'm finding it quite difficult, cookies don't help us, because whatsapp uses cookies and local storage. But I think I found a way, wait for it!

**Comment by xandao6** [comment]
Implemented in experimental branch
https://github.com/rpotter12/whatsapp-play/pull/103
