### ISSUE TITLE
Receive messages in wchat script (Request)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#77]
This code could help: https://github.com/zvovov/whatsapp-web

**Comment by rpotter12** [comment]
Thanks @xandao6. This will improve wchat :)

**Comment by kancherlakishorereddy** [comment]
iI am aGSSoC participant. Actually I was trying out wplay chatting with my friend and this was the first thing I observed. I was able to send messages but couldn't read his replies in the command line itself. I thought it would be nice to have that feature too. I am happy to know that you already have this in mind. Can I work on this under GSSoC2020?

Looking forward to doing more. Cheers!!

**Comment by xandao6** [comment]
@kancherlakishorereddy  Hi, take a look at https://github.com/rpotter12/whatsapp-play/issues/77

**Comment by kancherlakishorereddy** [comment]
I spent the last few days learning threading and scheduling. I am learning how to use pyppeterr. In less than a few days, I will go on and implement this feature. So can you extend the deadline by three more days?

**Comment by xandao6** [comment]
@kancherlakishorereddy I will extend for 4 days

**Comment by kancherlakishorereddy** [comment]
I am Struck at extracting content from the return handles. I am working on it, but i might need few more days. Can you extend the last date?

**Comment by xandao6** [comment]
@kancherlakishorereddy how is it going?

**Comment by smriti111** [comment]
Hi! i'm intrested to work on this issue.

**Comment by xandao6** [comment]
@smriti111 assigned

**Comment by kancherlakishorereddy** [comment]
Hi, I couldn't finish that last part .  It's better someone else work in that. @smriti111 if  you would like to know about my approach or something else contact me on slack. All the best👍👍

**Comment by Rits1272** [comment]
@xandao6 @rpotter12 can I work on this issue?

**Comment by cutzenfriend** [comment]
+1 for this!
