### ISSUE TITLE
News (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#80]
A script that let you receive news in a whatsapp group.

**Comment by simran2104** [comment]
can u explain something more about how to solve this issue.

**Comment by xandao6** [comment]
@simran2104 Is a script that after you choose a target (that part is already implemented), the script will be sending news from some sites to that target. This script is very interesting and should be written thinking about the improvements it may have in the future, how to choose the sites and the type of news, since people speak different languages.

**Comment by amandhamija98** [comment]
Hi, I would like to work on this issue, could I please be assigned

**Comment by xandao6** [comment]
@amandhamija98 assigned

**Comment by Rits1272** [comment]
Can I work on this issue @xandao6 @rpotter12? I think that @amandhamija98 is working on #82.

**Comment by xandao6** [comment]
@Rits1272 people can work in more than one issue, wait for more 3 days to be assigned.

**Comment by amandhamija98** [comment]
Hi, for getting news, I would have to web scrape, right? If so, are there any particular sights I should target?

**Comment by Rits1272** [comment]
I think you can also use an API. There are already many news api

**Comment by amandhamija98** [comment]
Thanks, I'll explore that.
Could I please extend my deadline, I need more time to do this

**Comment by xandao6** [comment]
@Rits1272 you could say yes or no to @amandhamija98, the deadline is in 1 day.

**Comment by Rits1272** [comment]
@amandhamija98 currently I am not working on any other issue. So kindly can you please let me take this issue?

**Comment by amandhamija98** [comment]
@Rits1272 , sure ,go ahead

**Comment by Rits1272** [comment]
Please assign this issue @xandao6 @rpotter12
