### ISSUE TITLE
Get pictures (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#81]
Get a picture of all contacts and save to a folder.

**Comment by sim12cool** [comment]
please assign this issue to me for gssoc

**Comment by sim12cool** [comment]
@rpotter12 please assign this issue to me.Thanks

**Comment by rpotter12** [comment]
@sim12cool Go ahead with your implementation :)

**Comment by sim12cool** [comment]
Thanks @rpotter12  :)

**Comment by Pihu1998** [comment]
Hey, I would like to work on this issue. Can you provide me with some insights of it? It would be really helpful. :)

**Comment by xandao6** [comment]
@Pihu1998 Assigned

**Comment by xandao6** [comment]
@Pihu1998 how is it going?

**Comment by Rits1272** [comment]
May I work on this issue @xandao6 @rpotter12?
