### ISSUE TITLE
Get name and number from all contacts (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#82]

**Comment by amandhamija98** [comment]
Hi, I would like to work on this enhancement feature, could you please tell me more about it

**Comment by xandao6** [comment]
> Hi, I would like to work on this enhancement feature, could you please tell me more about it

Hi, take a look on how the others scripts work, like the messageblast.py and onlinetracker.py.
You also need to add the new script to the file __main__.py.
In the utils folder you will find the "FOR SCRIPTING"  functions inside the files. These functions are the ones that you can use in your script (maybe we need to add more).

**Comment by xandao6** [comment]
Yea, you will have to create a new script in utils, a script to with functions that get the person's name and number using pyppeteer. Something similar to pyppeteerSearch.py ​​whose job is to search for a person on whatsapp from a name.

**Comment by amandhamija98** [comment]
I will do so, thank you!

**Comment by xandao6** [comment]
@amandhamija98  assigned to you, you have 4 days.

**Comment by xandao6** [comment]
@amandhamija98 deadline extended +4d

**Comment by amandhamija98** [comment]
Hey, I have just started work on this as I was hoping to use the same approach in issue 144. That got approved today, may i get some more time please. Thank you

**Comment by xandao6** [comment]
@amandhamija98 how is it going?

**Comment by amandhamija98** [comment]
Hi, I am working on implementing this feature in the new target search, will send a PR soon

**Comment by amandhamija98** [comment]
Hi, I have submitted a PR, kindly review it. Thanks
