### ISSUE TITLE
Download all media from one contact (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#84]

**Comment by poojasahu10** [comment]
@xandao6 : I have an idea for this issue. Once PR : [link](https://github.com/rpotter12/whatsapp-play/pull/184) is merged. I would like to discuss the idea.

**Comment by xandao6** [comment]
@poojasahu10 I'm waiting for someone to fix the selectors first, then I will test and merge your PR and assign you here.

**Comment by poojasahu10** [comment]
@xandao6 : Kindly assign this issue to me. Thanks.

**Comment by xandao6** [comment]
@poojasahu10  assigned

**Comment by poojasahu10** [comment]
@xandao6 : Can you elaborate this use case? Is it to save all the media from the contact on local machine disk or to download the media content manually when auto download is disabled for a contac.

**Comment by xandao6** [comment]
@poojasahu10 the first option, open the gallery and download the media to the disk.

**Comment by poojasahu10** [comment]
@xandao6 : I could download the media from one contact but it auto saves to downloads folder and both sent and received media is downloaded. Please let me know if the implementation scenario is correct and I will then raise a PR. Thanks.

**Comment by xandao6** [comment]
@poojasahu10 ok

**Comment by poojasahu10** [comment]
@xandao6 : I am trying with one approach with expose function can I get an extension on this issue ?

**Comment by xandao6** [comment]
yes

**Comment by xandao6** [comment]
@poojasahu10 how is it going?

**Comment by iharshit009** [comment]
@poojasahu10 if you aren't working on this, than @xandao6 could I work on it?

**Comment by rpotter12** [comment]
@iharshit009 You are assigned :)

@poojasahu10 is responding from a long time.

**Comment by iharshit009** [comment]
> @iharshit009 You are assigned :)
> 
> @poojasahu10 is responding from a long time.

thanks @rpotter12 I am starting my work on this

**Comment by iharshit009** [comment]
@rpotter12 @xandao6 I am getting difficulty in finding the nodes for the selectors Could you please help out??


    'media_links_docs':'#app > div > div > div._2aMzp > div._10V4p._1mseJ > span > div > span > div > div > div._3s5Z_ > div._2LSbZ._2j5ir._2ZVEo > div._3EN0l > div > div > div._1kz4p.VfNCr > span',
    'contact_name': '#main > header > div._1SwuT > div > img',
    'select_media_tick' : '#app > div > div > div._2aMzp > div._10V4p._1mseJ > span > div > span > div > div.rK2ei > span > div > div > div',
    'download_media_button':'#app > div > div > div._2aMzp > div._10V4p._1mseJ > span > div > span > div > div._2aUit._2XHj8 > button:nth-child(6) > span'
This is what I have found but there seems to occur an error...

> Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/harshit/Desktop/projects/whatsapp-play/wplay/__main__.py", line 159, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/harshit/Desktop/projects/whatsapp-play/wplay/__main__.py", line 152, in main
    await get_and_match_args(parser)
  File "/home/harshit/Desktop/projects/whatsapp-play/wplay/__main__.py", line 139, in get_and_match_args
    await downloadMedia.download_media(args.target)
  File "/home/harshit/Desktop/projects/whatsapp-play/wplay/downloadMedia.py", line 23, in download_media
    await page.click(whatsapp_selectors_dict['contact_info_page_elements'])
  File "/home/harshit/.local/lib/python3.6/site-packages/pyppeteer/page.py", line 1507, in click
    await frame.click(selector, options, **kwargs)
  File "/home/harshit/.local/lib/python3.6/site-packages/pyppeteer/frame_manager.py", line 569, in click
    raise PageError('No node found for selector: ' + selector)
pyppeteer.errors.PageError: No node found for selector: #app > div > div > div:nth-child(2) > div:last-of-type > span > div > span > div > div > div:first-child > div

Could you please help me ???
Or should I make a PR to know more about it??

**Comment by Rits1272** [comment]
@iharshit009 please remove the dynamic classes name from the selector. They change every time on load

**Comment by xandao6** [comment]
@iharshit009 yes, like @Rits1272  said, try not to use: first-child, nth-child(2), last-of-type.
In your whatsapp web, try to get the selectors using development tools (press F12 in Chrome) and ensure that works every time.

**Comment by iharshit009** [comment]
> @iharshit009 yes, like @Rits1272 said, try not to use: first-child, nth-child(2), last-of-type.
> In your whatsapp web, try to get the selectors using development tools (press F12 in Chrome) and ensure that works every time.

@xandao6 I just got a query, I have looked over the best way to solve it.. that is to select all the images through a checkbox tick on top of all the images... but those tick appear only when you tick at least one of the pics...

So I could not go with the above approach and now I need to download each image and move to the next  image.. and continue till the end ...

@rpotter12 @xandao6 Could you suggest any different better approach ?

**Comment by xandao6** [comment]
you can click in person name and open the gallery, then you can find your way to download the data

**Comment by xandao6** [comment]
Look how he does: https://github.com/rpotter12/whatsapp-play/pull/266

**Comment by xandao6** [comment]
You should download not only images but all media, but is just for one contact
