### ISSUE TITLE
Intermediate of a conversation (Idea)

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#87]
Let one person talk to another person from your whatsapp!

E.g.
Person A: send message to you
You: receive message from A and send the message to Person B
Person B: receive message from you

**Comment by safurazaheer** [comment]
Please assign this issue to me

**Comment by xandao6** [comment]
@safurazaheer if you have any question ask me here or in slack private.

**Comment by safurazaheer** [comment]
@xandao6   Basically, recieving the text can be solved by scrapping na?

**Comment by xandao6** [comment]
You need to find the right CSS Selector for the message, open your whatsapp web and try to undestand this.
![image](https://user-images.githubusercontent.com/22106326/75644464-286b0580-5c21-11ea-9d37-9cc03f3a1c29.png)

**Comment by xandao6** [comment]
@safurazaheer  deadline extended +4d

**Comment by HarsheetKakar** [comment]
can you give the url of slack channel? @xandao6

**Comment by safurazaheer** [comment]
@xandao6 I tried scrapping through selenuim and beautiful soup but I think this wont work fine coz it wont give the runtime result i.e we wont get the current message.

**Comment by xandao6** [comment]
@HarsheetKakar You are a GSSOC participant?

**Comment by xandao6** [comment]
@safurazaheer we use pyppeteer, we don't use selenium.

**Comment by HarsheetKakar** [comment]
> @HarsheetKakar You are a GSSOC participant?

yes

**Comment by xandao6** [comment]
@safurazaheer isn't hard to get the last message. You can do this with this selector: 
`#main > div > div > div > div > div:last-child > div > div > div > div.copyable-text > div`

**Comment by xandao6** [comment]
@HarsheetKakar search for proj_whatsapp-play inside gssoc slack

**Comment by xandao6** [comment]
@safurazaheer how is it going?

**Comment by Rits1272** [comment]
May I work on this issue @rpotter12 @xandao6?

**Comment by SinghHimadri** [comment]
I would like to work on this issue.Please assign it to me.
