### ISSUE TITLE
Outdated link.

### ISSUE THREAD

**Issue by xandao6** [rpotter12/whatsapp-play#89]
There is this link in the Readme that is outdated.
https://github.com/rpotter12/rpotter12.github.io/blob/master/blogs/blog3-tracking-26-07-2019.md

**Comment by xandao6** [comment]
Wait for Pyppeteer, things will be changed.

**Comment by rpotter12** [comment]
@xandao6 This blog is about the initial script so chat blog will not be changed. A new blog will be written for the new script :)
